import * as capnp from "../src/mod.ts";
import * as capnpAdvanced from "../src/advanced.ts";
import * as capnpEncoding from "../src/encoding.ts";
import { assertEquals } from "./test_utils.ts";

const EXPECTED_RUNTIME_EXPORTS = [
  "AbiError",
  "CAP_DESCRIPTOR_TAG_RECEIVER_HOSTED",
  "CAP_DESCRIPTOR_TAG_SENDER_HOSTED",
  "CapnpError",
  "CapnpFrameFramer",
  "CircuitBreaker",
  "DEFAULT_MAX_FRAME_BYTES",
  "DEFAULT_MAX_NESTING_DEPTH",
  "DEFAULT_MAX_SEGMENT_COUNT",
  "DEFAULT_MAX_TRAVERSAL_WORDS",
  "EMPTY_STRUCT_MESSAGE",
  "InMemoryRpcHarnessTransport",
  "InstantiationError",
  "MessagePortTransport",
  "MiddlewareTransport",
  "NetworkRpcHarnessTransport",
  "ProtocolError",
  "RETURN_TAG_EXCEPTION",
  "RETURN_TAG_RESULTS",
  "RPC_CALL_TARGET_TAG_IMPORTED_CAP",
  "RPC_CALL_TARGET_TAG_PROMISED_ANSWER",
  "RPC_MESSAGE_TAG_BOOTSTRAP",
  "RPC_MESSAGE_TAG_CALL",
  "RPC_MESSAGE_TAG_DISEMBARGO",
  "RPC_MESSAGE_TAG_FINISH",
  "RPC_MESSAGE_TAG_RELEASE",
  "RPC_MESSAGE_TAG_RESOLVE",
  "RPC_MESSAGE_TAG_RETURN",
  "RPC_PROMISED_ANSWER_OP_TAG_GET_POINTER_FIELD",
  "RPC_PROMISED_ANSWER_OP_TAG_NOOP",
  "ReconnectingRpcClientTransport",
  "RpcConnectionPool",
  "RpcPeer",
  "RpcPipeline",
  "RpcServerBridge",
  "RpcServerCallInterceptTransport",
  "RpcServerOutboundClient",
  "RpcServerRuntime",
  "RpcSession",
  "RpcWireClient",
  "RpcWireMessageBuilder",
  "SessionError",
  "SessionRpcClientTransport",
  "TcpTransport",
  "TransportError",
  "WebSocketTransport",
  "WebTransportTransport",
  "annotateCapnpError",
  "assertNonNegativeFinite",
  "assertNonNegativeInteger",
  "assertPositiveFinite",
  "assertPositiveInteger",
  "connect",
  "connectAndBootstrap",
  "connectTcpTransportWithReconnect",
  "connectTransportWithReconnect",
  "connectWebSocketTransportWithReconnect",
  "connectWebTransportTransportWithReconnect",
  "connectWithReconnect",
  "createDenoOtelObservability",
  "createExponentialBackoffReconnectPolicy",
  "createFrameSizeLimitMiddleware",
  "createLoggingMiddleware",
  "createRpcDebugTracer",
  "createRpcServiceToken",
  "createRpcIntrospectionMiddleware",
  "createRpcMetricsMiddleware",
  "createRpcSessionWithReconnect",
  "createStreamSender",
  "createWebTransportCertificateHash",
  "createWebTransportCertificateHashOptions",
  "decodeBootstrapRequestFrame",
  "decodeCallRequestFrame",
  "decodeFinishFrame",
  "decodeReleaseFrame",
  "decodeReturnFrame",
  "decodeRpcMessage",
  "decodeRpcMessageTag",
  "dispatchRpcMessage",
  "emitObservabilityEvent",
  "encodeBootstrapRequestFrame",
  "encodeBootstrapResponseFrame",
  "encodeCallRequestFrame",
  "encodeFinishFrame",
  "encodeReleaseFrame",
  "encodeReturnExceptionFrame",
  "encodeReturnResultsFrame",
  "extractBootstrapCapabilityIndex",
  "frameFromSegment",
  "formatRpcDebugEvent",
  "getWebTransportRuntimeSupport",
  "serve",
  "serveConnection",
  "segmentsFromFrame",
  "validateCapnpFrame",
  "withConnection",
].sort();

const EXPECTED_ENCODING_RUNTIME_EXPORTS = [
  "CAP_DESCRIPTOR_TAG_SENDER_HOSTED",
  "MessageBuilder",
  "MessageReader",
  "TYPE_ANY_POINTER",
  "TYPE_BOOL",
  "TYPE_DATA",
  "TYPE_FLOAT32",
  "TYPE_FLOAT64",
  "TYPE_INT16",
  "TYPE_INT32",
  "TYPE_INT64",
  "TYPE_INT8",
  "TYPE_INTERFACE",
  "TYPE_TEXT",
  "TYPE_UINT16",
  "TYPE_UINT32",
  "TYPE_UINT64",
  "TYPE_UINT8",
  "TYPE_VOID",
  "WORD_BYTES",
  "WasmSerde",
  "collectCapabilityPointersFromStruct",
  "decodeAnyPointerMessageFromReader",
  "decodeCapabilityPointerWord",
  "decodeDataField",
  "decodeListField",
  "decodePointerField",
  "decodeStructAt",
  "decodeStructMessage",
  "decodeStructMessageWithCaps",
  "defaultValueForType",
  "encodeAnyPointerMessageIntoBuilder",
  "encodeCapabilityPointerWord",
  "encodeDataField",
  "encodeListField",
  "encodePointerField",
  "encodeStructAt",
  "encodeStructMessage",
  "encodeStructMessageWithCaps",
  "enumOrdinal",
  "enumValue",
  "isDataType",
  "isPointerType",
  "isPresentField",
  "remapCapabilityIndices",
  "resolveActiveDiscriminant",
  "resolveDecodedCapabilities",
].sort();

Deno.test("public API runtime exports remain stable", () => {
  const actual = Object.keys(capnp).sort();
  assertEquals(
    JSON.stringify(actual),
    JSON.stringify(EXPECTED_RUNTIME_EXPORTS),
    "runtime export surface changed; update snapshot intentionally",
  );
});

Deno.test("encoding entrypoint runtime exports remain curated", () => {
  const actual = Object.keys(capnpEncoding).sort();
  assertEquals(
    JSON.stringify(actual),
    JSON.stringify(EXPECTED_ENCODING_RUNTIME_EXPORTS),
    "encoding export surface changed; update snapshot intentionally " +
      "(internal helpers such as MASK_29/asString/TEXT_ENCODER must stay " +
      "unexported)",
  );
});

Deno.test("advanced entrypoint exposes the low-level WASM surface", () => {
  const required = [
    "WasmAbi",
    "WasmPeer",
    "WasmSerde",
    "createRuntimePeer",
    "getCapnpWasmExports",
    "getRuntimeWasmExports",
    "instantiatePeer",
  ];
  const missing = required.filter((name) => !(name in capnpAdvanced));
  assertEquals(
    JSON.stringify(missing),
    JSON.stringify([]),
    "advanced entrypoint is missing low-level exports",
  );
});
