import * as capnp from "../mod.ts";
import { assertEquals } from "./test_utils.ts";

const EXPECTED_RUNTIME_EXPORTS = [
  "AbiError",
  "CapnpError",
  "CapnpFrameFramer",
  "CircuitBreaker",
  "DEFAULT_MAX_FRAME_BYTES",
  "DEFAULT_MAX_NESTING_DEPTH",
  "DEFAULT_MAX_SEGMENT_COUNT",
  "DEFAULT_MAX_TRAVERSAL_WORDS",
  "EMPTY_STRUCT_MESSAGE",
  "InMemoryRpcHarnessTransport",
  "InstantiationError",
  "MessagePortTransport",
  "MiddlewareTransport",
  "NetworkRpcHarnessTransport",
  "ProtocolError",
  "RPC_MESSAGE_TAG_BOOTSTRAP",
  "RPC_MESSAGE_TAG_CALL",
  "RPC_MESSAGE_TAG_DISEMBARGO",
  "RPC_MESSAGE_TAG_FINISH",
  "RPC_MESSAGE_TAG_RELEASE",
  "RPC_MESSAGE_TAG_RESOLVE",
  "RPC_MESSAGE_TAG_RETURN",
  "RPC_CALL_TARGET_TAG_IMPORTED_CAP",
  "RPC_CALL_TARGET_TAG_PROMISED_ANSWER",
  "RPC_PROMISED_ANSWER_OP_TAG_GET_POINTER_FIELD",
  "RPC_PROMISED_ANSWER_OP_TAG_NOOP",
  "ReconnectingRpcClientTransport",
  "RpcConnectionPool",
  "RpcPipeline",
  "RpcServerBridge",
  "RpcServerCallInterceptTransport",
  "RpcServerOutboundClient",
  "RpcServerRuntime",
  "RpcSession",
  "SessionError",
  "SessionRpcClientTransport",
  "TcpServerListener",
  "TcpTransport",
  "TransportError",
  "WebSocketTransport",
  "assertNonNegativeFinite",
  "assertNonNegativeInteger",
  "assertPositiveFinite",
  "assertPositiveInteger",
  "connectTcpTransportWithReconnect",
  "connectTransportWithReconnect",
  "connectWebSocketTransportWithReconnect",
  "connectWithReconnect",
  "createDenoOtelObservability",
  "createExponentialBackoffReconnectPolicy",
  "createFrameSizeLimitMiddleware",
  "createLoggingMiddleware",
  "createRpcIntrospectionMiddleware",
  "createRpcMetricsMiddleware",
  "createRpcSessionWithReconnect",
  "decodeBootstrapRequestFrame",
  "decodeCallRequestFrame",
  "decodeFinishFrame",
  "decodeReleaseFrame",
  "decodeReturnFrame",
  "decodeRpcMessage",
  "decodeRpcMessageTag",
  "dispatchRpcMessage",
  "emitObservabilityEvent",
  "encodeBootstrapRequestFrame",
  "encodeCallRequestFrame",
  "encodeFinishFrame",
  "encodeReleaseFrame",
  "encodeReturnExceptionFrame",
  "encodeReturnResultsFrame",
  "extractBootstrapCapabilityIndex",
  "validateCapnpFrame",
  "withConnection",
].sort();

Deno.test("public API runtime exports remain stable", () => {
  const actual = Object.keys(capnp).sort();
  assertEquals(
    JSON.stringify(actual),
    JSON.stringify(EXPECTED_RUNTIME_EXPORTS),
    "runtime export surface changed; update snapshot intentionally",
  );
});
