// End-to-end coverage for the capnpc-deno CLI write path: runs the real
// tools/capnpc-deno/main.ts as a subprocess (which shells out to the capnp
// compiler), so it needs the integration-tier permissions granted by
// `deno task test:codegen-e2e` plus a `capnp` binary on PATH.

import { assert } from "../test_utils.ts";

const CLI_MAIN = new URL("../../tools/capnpc-deno/main.ts", import.meta.url);
const PERSON_SCHEMA = new URL(
  "../fixtures/schemas/person_codegen.capnp",
  import.meta.url,
);
const UNION_SCHEMA = new URL(
  "../fixtures/schemas/union_group_codegen.capnp",
  import.meta.url,
);
const CROSSFILE_BASE_SCHEMA = new URL(
  "../fixtures/schemas/crossfile/base.capnp",
  import.meta.url,
);
const CROSSFILE_CONSUMER_SCHEMA = new URL(
  "../fixtures/schemas/crossfile/consumer.capnp",
  import.meta.url,
);
const CROSSFILE_DEEP_SCHEMA = new URL(
  "../fixtures/schemas/crossfile/nested/deep.capnp",
  import.meta.url,
);
const CLASH_A_SCHEMA = new URL(
  "../fixtures/schemas/crossfile/clash_a.capnp",
  import.meta.url,
);
const CLASH_B_SCHEMA = new URL(
  "../fixtures/schemas/crossfile/clash_b.capnp",
  import.meta.url,
);
const ENCODING_RUNTIME = new URL("../../src/encoding.ts", import.meta.url);
const RPC_RUNTIME = new URL("../../src/rpc.ts", import.meta.url);
const GENERATED_MODULE_HEADER = "// Generated by capnpc-deno";

// Schema and output paths are passed relative to `cwd` (the per-test temp
// directory) so generated module paths stay flat and the child process only
// needs write access inside that directory.
async function runCodegenCli(args: string[], cwd: string): Promise<void> {
  const command = new Deno.Command(Deno.execPath(), {
    args: [
      "run",
      "--allow-read",
      `--allow-write=${cwd}`,
      "--allow-run=capnp",
      CLI_MAIN.href,
      "generate",
      "--no-config",
      "--quiet",
      ...args,
    ],
    cwd,
    stdin: "null",
    stdout: "piped",
    stderr: "piped",
  });
  const output = await command.output();
  if (!output.success) {
    const stderr = new TextDecoder().decode(output.stderr);
    throw new Error(
      `capnpc-deno CLI exited with code ${output.code}: ${stderr.trimEnd()}`,
    );
  }
}

function assertBarrelExports(
  barrel: string,
  namespace: string,
  entry: string,
  message: string,
): void {
  assert(
    barrel.includes(`export * as ${namespace} from "./${entry}";`),
    message,
  );
}

async function isExistingFile(path: string): Promise<boolean> {
  try {
    return (await Deno.stat(path)).isFile;
  } catch {
    return false;
  }
}

Deno.test("capnpc-deno CLI e2e merges barrels across successive per-schema runs", async () => {
  // realPath keeps the child's --allow-write scope aligned with its cwd on
  // platforms where the temp directory sits behind a symlink (macOS /var).
  const tempRoot = await Deno.realPath(
    await Deno.makeTempDir({ prefix: "capnpc_deno_cli_e2e_" }),
  );
  try {
    await Deno.copyFile(PERSON_SCHEMA, `${tempRoot}/person_codegen.capnp`);
    await Deno.copyFile(UNION_SCHEMA, `${tempRoot}/union_group_codegen.capnp`);
    const outDir = `${tempRoot}/generated`;

    await runCodegenCli(
      ["--schema", "person_codegen.capnp", "--out", "generated"],
      tempRoot,
    );
    const firstBarrel = await Deno.readTextFile(`${outDir}/mod.ts`);
    assert(
      firstBarrel.startsWith(GENERATED_MODULE_HEADER),
      "expected first run to write a machine-generated barrel",
    );
    assertBarrelExports(
      firstBarrel,
      "personCodegen",
      "person_codegen_types.ts",
      "expected first run barrel to export the person types module",
    );

    await runCodegenCli(
      ["--schema", "union_group_codegen.capnp", "--out", "generated"],
      tempRoot,
    );
    const secondBarrel = await Deno.readTextFile(`${outDir}/mod.ts`);
    const expectedEntries: Array<[string, string]> = [
      ["personCodegenMeta", "person_codegen_meta.ts"],
      ["personCodegen", "person_codegen_types.ts"],
      ["unionGroupCodegenMeta", "union_group_codegen_meta.ts"],
      ["unionGroupCodegen", "union_group_codegen_types.ts"],
    ];
    for (const [namespace, entry] of expectedEntries) {
      assertBarrelExports(
        secondBarrel,
        namespace,
        entry,
        `expected merged barrel after second per-schema run to export ${entry}`,
      );
      assert(
        await isExistingFile(`${outDir}/${entry}`),
        `expected generated module ${entry} to exist on disk`,
      );
    }
  } finally {
    await Deno.remove(tempRoot, { recursive: true });
  }
});

Deno.test("capnpc-deno CLI e2e roots absolute --schema inputs at their common ancestor", async () => {
  // realPath keeps generated paths comparable on platforms where the temp
  // directory sits behind a symlink (macOS /var -> /private/var).
  const baseRoot = await Deno.realPath(
    await Deno.makeTempDir({ prefix: "capnpc_deno_cli_e2e_abs_" }),
  );
  try {
    // Two schemas with the SAME basename in sibling directories, passed as
    // absolute paths. capnp reports them as their full path minus the leading
    // "/", so before the fix both flattened to schema_types.ts and the run
    // aborted with an output-path collision. They must instead root at their
    // common ancestor, keeping the disambiguating directory.
    await Deno.mkdir(`${baseRoot}/a`, { recursive: true });
    await Deno.mkdir(`${baseRoot}/b`, { recursive: true });
    const outRoot = `${baseRoot}/out`;
    await Deno.mkdir(outRoot, { recursive: true });
    // Distinct file IDs (distinct schemas) avoid capnp's duplicate-ID error;
    // the shared basename is what forces the previously-colliding layout.
    await Deno.copyFile(PERSON_SCHEMA, `${baseRoot}/a/schema.capnp`);
    await Deno.copyFile(UNION_SCHEMA, `${baseRoot}/b/schema.capnp`);

    // Run from outRoot (not an ancestor of the schemas) so capnp reports the
    // stripped-absolute source names that trigger the bug.
    await runCodegenCli(
      [
        "--schema",
        `${baseRoot}/a/schema.capnp`,
        "--schema",
        `${baseRoot}/b/schema.capnp`,
        "--out",
        outRoot,
      ],
      outRoot,
    );

    const barrel = await Deno.readTextFile(`${outRoot}/mod.ts`);
    const expectedEntries: Array<[string, string]> = [
      ["aSchema", "a/schema_types.ts"],
      ["bSchema", "b/schema_types.ts"],
    ];
    for (const [namespace, entry] of expectedEntries) {
      assertBarrelExports(
        barrel,
        namespace,
        entry,
        `expected barrel to export ${entry} rooted at the common ancestor`,
      );
      assert(
        await isExistingFile(`${outRoot}/${entry}`),
        `expected generated module ${entry} to exist on disk`,
      );
    }
    assert(
      !barrel.includes('"./schema_types.ts"'),
      "expected no flattened schema_types.ts that would collide across the two inputs",
    );
  } finally {
    await Deno.remove(baseRoot, { recursive: true });
  }
});

Deno.test("capnpc-deno CLI e2e emits layout-correct cross-file imports that type-check", async () => {
  // realPath keeps the child's --allow-write scope aligned with its cwd on
  // platforms where the temp directory sits behind a symlink (macOS /var).
  const tempRoot = await Deno.realPath(
    await Deno.makeTempDir({ prefix: "capnpc_deno_cli_e2e_crossfile_" }),
  );
  try {
    await Deno.mkdir(`${tempRoot}/schema/nested`, { recursive: true });
    await Deno.copyFile(CROSSFILE_BASE_SCHEMA, `${tempRoot}/schema/base.capnp`);
    await Deno.copyFile(
      CROSSFILE_CONSUMER_SCHEMA,
      `${tempRoot}/schema/consumer.capnp`,
    );
    await Deno.copyFile(
      CROSSFILE_DEEP_SCHEMA,
      `${tempRoot}/schema/nested/deep.capnp`,
    );

    // Schema layout: modules mirror the schema tree, so the nested importer
    // must reach its dependency with a parent-relative specifier. The
    // namespaced barrel keeps same-named exports (shared runtime re-exports)
    // from colliding across the bundle's modules.
    await runCodegenCli(
      ["--src", "schema", "--out", "generated", "--layout", "schema"],
      tempRoot,
    );
    const crossfileBarrel = await Deno.readTextFile(
      `${tempRoot}/generated/mod.ts`,
    );
    const expectedBarrelEntries: Array<[string, string]> = [
      ["base", "base_types.ts"],
      ["baseMeta", "base_meta.ts"],
      ["consumer", "consumer_types.ts"],
      ["consumerMeta", "consumer_meta.ts"],
      ["nestedDeep", "nested/deep_types.ts"],
      ["nestedDeepMeta", "nested/deep_meta.ts"],
    ];
    for (const [namespace, entry] of expectedBarrelEntries) {
      assertBarrelExports(
        crossfileBarrel,
        namespace,
        entry,
        `expected crossfile barrel to namespace ${entry} as ${namespace}`,
      );
    }
    const consumer = await Deno.readTextFile(
      `${tempRoot}/generated/consumer_types.ts`,
    );
    assert(
      consumer.includes(
        'import type { Chunk, Level, Meta, Point, Watcher } from "./base_types.ts";',
      ),
      "expected consumer module to import cross-file types from its sibling",
    );
    assert(
      consumer.includes(
        "import { ChunkStruct, createWatcherClient, createWatcherServiceClient, " +
          'MetaStruct, PointStruct, Watcher as Watcher$Base } from "./base_types.ts";',
      ),
      "expected consumer module to import cross-file struct descriptors, the imported interface token, and its client factories",
    );
    const deep = await Deno.readTextFile(
      `${tempRoot}/generated/nested/deep_types.ts`,
    );
    assert(
      deep.includes('import type { Level, Point } from "../base_types.ts";'),
      "expected nested module to import cross-file types parent-relative",
    );
    assert(
      deep.includes('import { PointStruct } from "../base_types.ts";'),
      "expected nested module to import descriptors parent-relative",
    );

    // Flat layout: everything is a sibling, including the nested schema's
    // module.
    await runCodegenCli(
      ["--src", "schema", "--out", "flat", "--layout", "flat", "--no-barrel"],
      tempRoot,
    );
    const flatDeep = await Deno.readTextFile(`${tempRoot}/flat/deep_types.ts`);
    assert(
      flatDeep.includes(
        'import type { Level, Point } from "./base_types.ts";',
      ),
      "expected flat layout to keep sibling specifiers for nested schemas",
    );

    // The generated schema-layout bundle passes `deno check` strict with the
    // runtime mapped to this repo's sources.
    await Deno.writeTextFile(
      `${tempRoot}/deno.json`,
      JSON.stringify({
        imports: {
          "@nullstyle/capnp/encoding": ENCODING_RUNTIME.href,
          "@nullstyle/capnp/rpc": RPC_RUNTIME.href,
        },
        compilerOptions: { strict: true },
      }),
    );
    const check = new Deno.Command(Deno.execPath(), {
      args: [
        "check",
        "--config",
        `${tempRoot}/deno.json`,
        // mod.ts pulls in every generated module, so checking the barrel
        // covers the whole bundle and proves the namespaced re-exports do
        // not collide.
        `${tempRoot}/generated/mod.ts`,
      ],
      cwd: tempRoot,
      stdin: "null",
      stdout: "piped",
      stderr: "piped",
    });
    const checkOutput = await check.output();
    assert(
      checkOutput.success,
      `expected generated crossfile bundle to type-check: ${
        new TextDecoder().decode(checkOutput.stderr).trimEnd()
      }`,
    );
  } finally {
    await Deno.remove(tempRoot, { recursive: true });
  }
});

Deno.test("capnpc-deno CLI e2e namespaced barrel keeps same-named schemas reachable and type-checking", async () => {
  // clash_a.capnp and clash_b.capnp deliberately declare the same domain
  // struct name (UsageResult) and the same interface method name (ping): a
  // flat `export * from` barrel over both modules would collide on every
  // shared export. The namespaced barrel must type-check cleanly and expose
  // both schemas through distinct namespaces.
  const tempRoot = await Deno.realPath(
    await Deno.makeTempDir({ prefix: "capnpc_deno_cli_e2e_clash_" }),
  );
  try {
    await Deno.copyFile(CLASH_A_SCHEMA, `${tempRoot}/clash_a.capnp`);
    await Deno.copyFile(CLASH_B_SCHEMA, `${tempRoot}/clash_b.capnp`);

    await runCodegenCli(
      [
        "--schema",
        "clash_a.capnp",
        "--schema",
        "clash_b.capnp",
        "--out",
        "generated",
      ],
      tempRoot,
    );

    const barrel = await Deno.readTextFile(`${tempRoot}/generated/mod.ts`);
    const expectedEntries: Array<[string, string]> = [
      ["clashA", "clash_a_types.ts"],
      ["clashAMeta", "clash_a_meta.ts"],
      ["clashB", "clash_b_types.ts"],
      ["clashBMeta", "clash_b_meta.ts"],
    ];
    for (const [namespace, entry] of expectedEntries) {
      assertBarrelExports(
        barrel,
        namespace,
        entry,
        `expected clash barrel to namespace ${entry} as ${namespace}`,
      );
    }
    assert(
      !barrel.includes("export * from"),
      "expected no flat re-exports to remain in the clash barrel",
    );

    // Reach both namespaces at the type level (UsageResult differs per
    // schema) and the value level (codecs, interface tokens, meta consts),
    // then prove the whole bundle type-checks strict through the barrel.
    await Deno.writeTextFile(
      `${tempRoot}/probe.ts`,
      [
        'import { clashA, clashAMeta, clashB, clashBMeta } from "./generated/mod.ts";',
        "",
        "const a: clashA.UsageResult = { used: 1n, limit: 2n };",
        "const b: clashB.UsageResult = { used: 1n, quota: 2n };",
        "export const bytesA: Uint8Array = clashA.UsageResultCodec.encode(a);",
        "export const bytesB: Uint8Array = clashB.UsageResultCodec.encode(b);",
        "export const idA: bigint = clashA.MeteringInterfaceId;",
        "export const idB: bigint = clashB.HeartbeatInterfaceId;",
        "export const fileA: string = clashAMeta.schemaFilename;",
        "export const fileB: string = clashBMeta.schemaFilename;",
        "",
      ].join("\n"),
    );
    await Deno.writeTextFile(
      `${tempRoot}/deno.json`,
      JSON.stringify({
        imports: {
          "@nullstyle/capnp/encoding": ENCODING_RUNTIME.href,
          "@nullstyle/capnp/rpc": RPC_RUNTIME.href,
        },
        compilerOptions: { strict: true },
      }),
    );
    const check = new Deno.Command(Deno.execPath(), {
      args: [
        "check",
        "--config",
        `${tempRoot}/deno.json`,
        `${tempRoot}/generated/mod.ts`,
        `${tempRoot}/probe.ts`,
      ],
      cwd: tempRoot,
      stdin: "null",
      stdout: "piped",
      stderr: "piped",
    });
    const checkOutput = await check.output();
    assert(
      checkOutput.success,
      `expected clash bundle and namespace probe to type-check: ${
        new TextDecoder().decode(checkOutput.stderr).trimEnd()
      }`,
    );
  } finally {
    await Deno.remove(tempRoot, { recursive: true });
  }
});

Deno.test("capnpc-deno CLI e2e keeps overwrite semantics for --src directory runs", async () => {
  // realPath keeps the child's --allow-write scope aligned with its cwd on
  // platforms where the temp directory sits behind a symlink (macOS /var).
  const tempRoot = await Deno.realPath(
    await Deno.makeTempDir({ prefix: "capnpc_deno_cli_e2e_" }),
  );
  try {
    await Deno.mkdir(`${tempRoot}/src_only_union`, { recursive: true });
    await Deno.copyFile(
      UNION_SCHEMA,
      `${tempRoot}/src_only_union/union_group_codegen.capnp`,
    );
    await Deno.copyFile(PERSON_SCHEMA, `${tempRoot}/person_codegen.capnp`);
    const outDir = `${tempRoot}/generated`;

    // Seed the output directory with an earlier per-schema run so a merge
    // would have preserved its barrel entries.
    await runCodegenCli(
      ["--schema", "person_codegen.capnp", "--out", "generated"],
      tempRoot,
    );
    const seededBarrel = await Deno.readTextFile(`${outDir}/mod.ts`);
    assertBarrelExports(
      seededBarrel,
      "personCodegen",
      "person_codegen_types.ts",
      "expected seeding run barrel to export the person types module",
    );

    await runCodegenCli(
      ["--src", "src_only_union", "--out", "generated"],
      tempRoot,
    );
    const barrel = await Deno.readTextFile(`${outDir}/mod.ts`);
    assertBarrelExports(
      barrel,
      "unionGroupCodegen",
      "union_group_codegen_types.ts",
      "expected --src run barrel to export the union types module",
    );
    assert(
      !barrel.includes("person_codegen_types.ts"),
      "expected --src run to overwrite the barrel and drop earlier per-schema entries",
    );
    assert(
      await isExistingFile(`${outDir}/person_codegen_types.ts`),
      "expected earlier person module to still exist on disk, proving the barrel entry was dropped by overwrite semantics rather than a missing file",
    );
  } finally {
    await Deno.remove(tempRoot, { recursive: true });
  }
});
