// End-to-end coverage for the capnpc-deno CLI write path: runs the real
// tools/capnpc-deno/main.ts as a subprocess (which shells out to the capnp
// compiler), so it needs the integration-tier permissions granted by
// `deno task test:codegen-e2e` plus a `capnp` binary on PATH.

import { assert } from "../test_utils.ts";

const CLI_MAIN = new URL("../../tools/capnpc-deno/main.ts", import.meta.url);
const PERSON_SCHEMA = new URL(
  "../fixtures/schemas/person_codegen.capnp",
  import.meta.url,
);
const UNION_SCHEMA = new URL(
  "../fixtures/schemas/union_group_codegen.capnp",
  import.meta.url,
);
const GENERATED_MODULE_HEADER = "// Generated by capnpc-deno";

// Schema and output paths are passed relative to `cwd` (the per-test temp
// directory) so generated module paths stay flat and the child process only
// needs write access inside that directory.
async function runCodegenCli(args: string[], cwd: string): Promise<void> {
  const command = new Deno.Command(Deno.execPath(), {
    args: [
      "run",
      "--allow-read",
      `--allow-write=${cwd}`,
      "--allow-run=capnp",
      CLI_MAIN.href,
      "generate",
      "--no-config",
      "--quiet",
      ...args,
    ],
    cwd,
    stdin: "null",
    stdout: "piped",
    stderr: "piped",
  });
  const output = await command.output();
  if (!output.success) {
    const stderr = new TextDecoder().decode(output.stderr);
    throw new Error(
      `capnpc-deno CLI exited with code ${output.code}: ${stderr.trimEnd()}`,
    );
  }
}

function assertBarrelExports(
  barrel: string,
  entry: string,
  message: string,
): void {
  assert(barrel.includes(`export * from "./${entry}";`), message);
}

async function isExistingFile(path: string): Promise<boolean> {
  try {
    return (await Deno.stat(path)).isFile;
  } catch {
    return false;
  }
}

Deno.test("capnpc-deno CLI e2e merges barrels across successive per-schema runs", async () => {
  // realPath keeps the child's --allow-write scope aligned with its cwd on
  // platforms where the temp directory sits behind a symlink (macOS /var).
  const tempRoot = await Deno.realPath(
    await Deno.makeTempDir({ prefix: "capnpc_deno_cli_e2e_" }),
  );
  try {
    await Deno.copyFile(PERSON_SCHEMA, `${tempRoot}/person_codegen.capnp`);
    await Deno.copyFile(UNION_SCHEMA, `${tempRoot}/union_group_codegen.capnp`);
    const outDir = `${tempRoot}/generated`;

    await runCodegenCli(
      ["--schema", "person_codegen.capnp", "--out", "generated"],
      tempRoot,
    );
    const firstBarrel = await Deno.readTextFile(`${outDir}/mod.ts`);
    assert(
      firstBarrel.startsWith(GENERATED_MODULE_HEADER),
      "expected first run to write a machine-generated barrel",
    );
    assertBarrelExports(
      firstBarrel,
      "person_codegen_types.ts",
      "expected first run barrel to export the person types module",
    );

    await runCodegenCli(
      ["--schema", "union_group_codegen.capnp", "--out", "generated"],
      tempRoot,
    );
    const secondBarrel = await Deno.readTextFile(`${outDir}/mod.ts`);
    const expectedEntries = [
      "person_codegen_meta.ts",
      "person_codegen_types.ts",
      "union_group_codegen_meta.ts",
      "union_group_codegen_types.ts",
    ];
    for (const entry of expectedEntries) {
      assertBarrelExports(
        secondBarrel,
        entry,
        `expected merged barrel after second per-schema run to export ${entry}`,
      );
      assert(
        await isExistingFile(`${outDir}/${entry}`),
        `expected generated module ${entry} to exist on disk`,
      );
    }
  } finally {
    await Deno.remove(tempRoot, { recursive: true });
  }
});

Deno.test("capnpc-deno CLI e2e roots absolute --schema inputs at their common ancestor", async () => {
  // realPath keeps generated paths comparable on platforms where the temp
  // directory sits behind a symlink (macOS /var -> /private/var).
  const baseRoot = await Deno.realPath(
    await Deno.makeTempDir({ prefix: "capnpc_deno_cli_e2e_abs_" }),
  );
  try {
    // Two schemas with the SAME basename in sibling directories, passed as
    // absolute paths. capnp reports them as their full path minus the leading
    // "/", so before the fix both flattened to schema_types.ts and the run
    // aborted with an output-path collision. They must instead root at their
    // common ancestor, keeping the disambiguating directory.
    await Deno.mkdir(`${baseRoot}/a`, { recursive: true });
    await Deno.mkdir(`${baseRoot}/b`, { recursive: true });
    const outRoot = `${baseRoot}/out`;
    await Deno.mkdir(outRoot, { recursive: true });
    // Distinct file IDs (distinct schemas) avoid capnp's duplicate-ID error;
    // the shared basename is what forces the previously-colliding layout.
    await Deno.copyFile(PERSON_SCHEMA, `${baseRoot}/a/schema.capnp`);
    await Deno.copyFile(UNION_SCHEMA, `${baseRoot}/b/schema.capnp`);

    // Run from outRoot (not an ancestor of the schemas) so capnp reports the
    // stripped-absolute source names that trigger the bug.
    await runCodegenCli(
      [
        "--schema",
        `${baseRoot}/a/schema.capnp`,
        "--schema",
        `${baseRoot}/b/schema.capnp`,
        "--out",
        outRoot,
      ],
      outRoot,
    );

    const barrel = await Deno.readTextFile(`${outRoot}/mod.ts`);
    for (const entry of ["a/schema_types.ts", "b/schema_types.ts"]) {
      assertBarrelExports(
        barrel,
        entry,
        `expected barrel to export ${entry} rooted at the common ancestor`,
      );
      assert(
        await isExistingFile(`${outRoot}/${entry}`),
        `expected generated module ${entry} to exist on disk`,
      );
    }
    assert(
      !barrel.includes('export * from "./schema_types.ts";'),
      "expected no flattened schema_types.ts that would collide across the two inputs",
    );
  } finally {
    await Deno.remove(baseRoot, { recursive: true });
  }
});

Deno.test("capnpc-deno CLI e2e keeps overwrite semantics for --src directory runs", async () => {
  // realPath keeps the child's --allow-write scope aligned with its cwd on
  // platforms where the temp directory sits behind a symlink (macOS /var).
  const tempRoot = await Deno.realPath(
    await Deno.makeTempDir({ prefix: "capnpc_deno_cli_e2e_" }),
  );
  try {
    await Deno.mkdir(`${tempRoot}/src_only_union`, { recursive: true });
    await Deno.copyFile(
      UNION_SCHEMA,
      `${tempRoot}/src_only_union/union_group_codegen.capnp`,
    );
    await Deno.copyFile(PERSON_SCHEMA, `${tempRoot}/person_codegen.capnp`);
    const outDir = `${tempRoot}/generated`;

    // Seed the output directory with an earlier per-schema run so a merge
    // would have preserved its barrel entries.
    await runCodegenCli(
      ["--schema", "person_codegen.capnp", "--out", "generated"],
      tempRoot,
    );
    const seededBarrel = await Deno.readTextFile(`${outDir}/mod.ts`);
    assertBarrelExports(
      seededBarrel,
      "person_codegen_types.ts",
      "expected seeding run barrel to export the person types module",
    );

    await runCodegenCli(
      ["--src", "src_only_union", "--out", "generated"],
      tempRoot,
    );
    const barrel = await Deno.readTextFile(`${outDir}/mod.ts`);
    assertBarrelExports(
      barrel,
      "union_group_codegen_types.ts",
      "expected --src run barrel to export the union types module",
    );
    assert(
      !barrel.includes("person_codegen_types.ts"),
      "expected --src run to overwrite the barrel and drop earlier per-schema entries",
    );
    assert(
      await isExistingFile(`${outDir}/person_codegen_types.ts`),
      "expected earlier person module to still exist on disk, proving the barrel entry was dropped by overwrite semantics rather than a missing file",
    );
  } finally {
    await Deno.remove(tempRoot, { recursive: true });
  }
});
