/**
 * Interface/RPC client and server emission functions.
 */

import type { NodeModel } from "./model.ts";
import type { InterfaceInfo, StructInfo } from "./emitter_helpers.ts";
import {
  collectLocalInterfaces,
  collectLocalTypes,
  formatBigint,
  quoteIfNeeded,
  toCamelCase,
} from "./emitter_helpers.ts";

export function emitRpcModule(
  fileNode: NodeModel,
  nodeById: Map<bigint, NodeModel>,
  capnpModulePath: string,
): string {
  const out: string[] = [];
  out.push("// Generated by capnpc-deno");
  out.push("// DO NOT EDIT MANUALLY.");
  out.push("");

  const localTypes = collectLocalTypes(fileNode, nodeById);
  const structById = new Map(
    localTypes.structInfos.map((item) => [item.id, item] as const),
  );
  const interfaces = collectLocalInterfaces(fileNode, nodeById);

  if (interfaces.length === 0) {
    out.push("export {};");
    out.push("");
    return out.join("\n");
  }

  const typeImports = new Set<string>(["CapabilityPointer"]);
  const valueImports = new Set<string>();

  for (const info of interfaces) {
    const methods = info.node.interfaceNode?.methods
      .slice()
      .sort((a, b) =>
        (a.codeOrder - b.codeOrder) || a.name.localeCompare(b.name)
      ) ??
      [];
    for (const method of methods) {
      const params = structById.get(method.paramStructTypeId);
      const results = structById.get(method.resultStructTypeId);
      if (params) {
        typeImports.add(params.typeName);
        valueImports.add(params.codecConst);
      }
      if (results) {
        typeImports.add(results.typeName);
        valueImports.add(results.codecConst);
      }
    }
  }

  const sortedTypeImports = [...typeImports].sort((left, right) =>
    left.localeCompare(right)
  );
  const sortedValueImports = [...valueImports].sort((left, right) =>
    left.localeCompare(right)
  );
  out.push(
    `import type { ${sortedTypeImports.join(", ")} } from ${
      JSON.stringify(`./${capnpModulePath}`)
    };`,
  );
  if (sortedValueImports.length > 0) {
    out.push(
      `import { ${sortedValueImports.join(", ")} } from ${
        JSON.stringify(`./${capnpModulePath}`)
      };`,
    );
  }
  out.push("");
  out.push("export interface RpcCallOptions {");
  out.push("  signal?: AbortSignal;");
  out.push("  timeoutMs?: number;");
  out.push("  onQuestionId?: (questionId: number) => void;");
  out.push("  autoFinish?: boolean;");
  out.push("  finish?: RpcFinishOptions;");
  out.push("}");
  out.push("");
  out.push("export interface RpcFinishOptions {");
  out.push("  releaseResultCaps?: boolean;");
  out.push("  requireEarlyCancellation?: boolean;");
  out.push("}");
  out.push("");
  out.push("export interface RpcCallContext {");
  out.push("  readonly capability: CapabilityPointer;");
  out.push("  readonly methodId: number;");
  out.push("  readonly questionId?: number;");
  out.push("  readonly interfaceId?: bigint;");
  out.push("}");
  out.push("");
  out.push("export interface RpcClientTransport {");
  out.push("  call(");
  out.push("    capability: CapabilityPointer,");
  out.push("    methodId: number,");
  out.push("    params: Uint8Array,");
  out.push("    options?: RpcCallOptions,");
  out.push("  ): Promise<Uint8Array>;");
  out.push(
    "  finish?(questionId: number, options?: RpcFinishOptions): Promise<void> | void;",
  );
  out.push(
    "  release?(capability: CapabilityPointer, referenceCount?: number): Promise<void> | void;",
  );
  out.push("}");
  out.push("");
  out.push("export interface RpcServerDispatch {");
  out.push("  readonly interfaceId: bigint;");
  out.push("  dispatch(");
  out.push("    methodId: number,");
  out.push("    params: Uint8Array,");
  out.push("    ctx: RpcCallContext,");
  out.push("  ): Promise<Uint8Array>;");
  out.push("}");
  out.push("");
  out.push(
    "export interface RpcBootstrapClientTransport extends RpcClientTransport {",
  );
  out.push(
    "  bootstrap(options?: RpcCallOptions): Promise<CapabilityPointer>;",
  );
  out.push("}");
  out.push("");
  out.push("export interface RpcExportCapabilityOptions {");
  out.push("  capabilityIndex?: number;");
  out.push("  referenceCount?: number;");
  out.push("}");
  out.push("");
  out.push("export interface RpcServerRegistry {");
  out.push("  exportCapability(");
  out.push("    dispatch: RpcServerDispatch,");
  out.push("    options?: RpcExportCapabilityOptions,");
  out.push("  ): CapabilityPointer;");
  out.push("}");
  out.push("");

  for (const info of interfaces) {
    emitInterfaceCode(out, info, structById);
  }

  return out.join("\n");
}

function emitInterfaceCode(
  out: string[],
  info: InterfaceInfo,
  structById: Map<bigint, StructInfo>,
): void {
  const methods = info.node.interfaceNode?.methods
    .slice()
    .sort((a, b) =>
      (a.codeOrder - b.codeOrder) || a.name.localeCompare(b.name)
    ) ??
    [];
  const usedMethodNames = new Set<string>();
  const resolvedMethods: Array<{
    method: (typeof methods)[number];
    methodName: string;
    params: StructInfo;
    results: StructInfo;
  }> = [];

  for (const method of methods) {
    const baseName = toCamelCase(method.name);
    let methodName = baseName;
    let suffix = 2;
    while (usedMethodNames.has(methodName)) {
      methodName = `${baseName}${suffix}`;
      suffix += 1;
    }
    usedMethodNames.add(methodName);

    const params = structById.get(method.paramStructTypeId);
    if (!params) {
      throw new Error(
        `interface ${info.typeName} method ${
          JSON.stringify(method.name)
        } references unknown param struct id ${
          formatBigint(method.paramStructTypeId)
        }`,
      );
    }
    const results = structById.get(method.resultStructTypeId);
    if (!results) {
      throw new Error(
        `interface ${info.typeName} method ${
          JSON.stringify(method.name)
        } references unknown result struct id ${
          formatBigint(method.resultStructTypeId)
        }`,
      );
    }

    resolvedMethods.push({
      method,
      methodName,
      params,
      results,
    });
  }

  out.push(
    `export const ${info.typeName}InterfaceId = ${formatBigint(info.id)};`,
  );
  out.push("");
  out.push(`export const ${info.typeName}MethodOrdinals = {`);
  for (const resolved of resolvedMethods) {
    out.push(
      `  ${quoteIfNeeded(resolved.methodName)}: ${resolved.method.codeOrder},`,
    );
  }
  out.push("} as const;");
  out.push("");

  out.push(`export interface ${info.typeName}Client {`);
  for (const resolved of resolvedMethods) {
    out.push(
      `  ${
        quoteIfNeeded(resolved.methodName)
      }(params: ${resolved.params.typeName}, options?: RpcCallOptions): Promise<${resolved.results.typeName}>;`,
    );
  }
  out.push("}");
  out.push("");

  out.push(`export interface ${info.typeName}Server {`);
  for (const resolved of resolvedMethods) {
    out.push(
      `  ${
        quoteIfNeeded(resolved.methodName)
      }(params: ${resolved.params.typeName}, ctx: RpcCallContext): Promise<${resolved.results.typeName}> | ${resolved.results.typeName};`,
    );
  }
  out.push("}");
  out.push("");

  out.push(
    `export function create${info.typeName}Client(transport: RpcClientTransport, capability: CapabilityPointer): ${info.typeName}Client {`,
  );
  out.push("  return {");
  for (const resolved of resolvedMethods) {
    out.push(
      `    ${
        quoteIfNeeded(resolved.methodName)
      }: async (params: ${resolved.params.typeName}, options?: RpcCallOptions): Promise<${resolved.results.typeName}> => {`,
    );
    out.push(
      `      const payload = ${resolved.params.codecConst}.encode(params);`,
    );
    out.push("      let questionId: number | undefined;");
    out.push("      const callOptions: RpcCallOptions = {");
    out.push("        ...(options ?? {}),");
    out.push("        onQuestionId: (value: number): void => {");
    out.push("          questionId = value;");
    out.push("          options?.onQuestionId?.(value);");
    out.push("        },");
    out.push("      };");
    out.push(
      `      const response = await transport.call(capability, ${info.typeName}MethodOrdinals[${
        JSON.stringify(resolved.methodName)
      }], payload, callOptions);`,
    );
    out.push("      try {");
    out.push(`        return ${resolved.results.codecConst}.decode(response);`);
    out.push("      } finally {");
    out.push(
      "        if ((options?.autoFinish ?? true) && questionId !== undefined && transport.finish) {",
    );
    out.push("          await transport.finish(questionId, options?.finish);");
    out.push("        }");
    out.push("      }");
    out.push("    },");
  }
  out.push("  };");
  out.push("}");
  out.push("");
  out.push(`export async function bootstrap${info.typeName}Client(`);
  out.push("  transport: RpcBootstrapClientTransport,");
  out.push("  options?: RpcCallOptions,");
  out.push(`): Promise<${info.typeName}Client> {`);
  out.push("  const capability = await transport.bootstrap(options);");
  out.push(`  return create${info.typeName}Client(transport, capability);`);
  out.push("}");
  out.push("");

  out.push(
    `export function create${info.typeName}Server(server: ${info.typeName}Server): RpcServerDispatch {`,
  );
  out.push("  return {");
  out.push(`    interfaceId: ${info.typeName}InterfaceId,`);
  out.push(
    "    dispatch: async (methodId: number, params: Uint8Array, ctx: RpcCallContext): Promise<Uint8Array> => {",
  );
  out.push("      switch (methodId) {");
  for (const resolved of resolvedMethods) {
    out.push(`        case ${resolved.method.codeOrder}: {`);
    out.push(
      `          const decoded = ${resolved.params.codecConst}.decode(params);`,
    );
    out.push(
      `          const result = await server[${
        JSON.stringify(resolved.methodName)
      }](decoded, ctx);`,
    );
    out.push(`          return ${resolved.results.codecConst}.encode(result);`);
    out.push("        }");
  }
  out.push("        default:");
  out.push('          throw new Error("unknown method ordinal: " + methodId);');
  out.push("      }");
  out.push("    },");
  out.push("  };");
  out.push("}");
  out.push("");
  out.push(`export function register${info.typeName}Server(`);
  out.push("  registry: RpcServerRegistry,");
  out.push(`  server: ${info.typeName}Server,`);
  out.push("  options: RpcExportCapabilityOptions = {},");
  out.push("): CapabilityPointer {");
  out.push(
    `  return registry.exportCapability(create${info.typeName}Server(server), options);`,
  );
  out.push("}");
  out.push("");
}
