/**
 * Schema metadata emission functions.
 */

import type { NodeModel, RequestedFileModel } from "./model.ts";
import {
  collectLocalInterfaces,
  formatBigint,
} from "./emitter_helpers.ts";

export function emitMetaModule(
  requested: RequestedFileModel,
  fileNode: NodeModel,
  nodeById: Map<bigint, NodeModel>,
): string {
  const out: string[] = [];
  out.push("// Generated by capnpc-deno");
  out.push("// DO NOT EDIT MANUALLY.");
  out.push("");

  const prefix = `${fileNode.displayName}:`;
  const localNodes = [...nodeById.values()].filter((node) =>
    node.displayName === fileNode.displayName || node.displayName.startsWith(prefix)
  ).sort((left, right) => left.displayName.localeCompare(right.displayName));
  const interfaces = collectLocalInterfaces(fileNode, nodeById);

  out.push(`export const schemaFileId = ${formatBigint(fileNode.id)};`);
  out.push(`export const schemaFilename = ${JSON.stringify(requested.filename)};`);
  out.push("");
  out.push("export const schemaImports = [");
  for (const item of requested.imports) {
    out.push("  {");
    out.push(`    id: ${formatBigint(item.id)},`);
    out.push(`    name: ${JSON.stringify(item.name)},`);
    out.push("  },");
  }
  out.push("] as const;");
  out.push("");
  out.push("export const schemaNodes = [");
  for (const node of localNodes) {
    out.push("  {");
    out.push(`    id: ${formatBigint(node.id)},`);
    out.push(`    kind: ${JSON.stringify(node.kind)},`);
    out.push(`    displayName: ${JSON.stringify(node.displayName)},`);
    out.push(`    scopeId: ${formatBigint(node.scopeId)},`);
    out.push("  },");
  }
  out.push("] as const;");
  out.push("");
  out.push("export const interfaceMethods = [");
  for (const info of interfaces) {
    const methods = info.node.interfaceNode?.methods
      .slice()
      .sort((a, b) => (a.codeOrder - b.codeOrder) || a.name.localeCompare(b.name)) ??
      [];
    for (const method of methods) {
      out.push("  {");
      out.push(`    interfaceId: ${formatBigint(info.id)},`);
      out.push(`    interfaceName: ${JSON.stringify(info.typeName)},`);
      out.push(`    methodName: ${JSON.stringify(method.name)},`);
      out.push(`    codeOrder: ${method.codeOrder},`);
      out.push(`    paramStructTypeId: ${formatBigint(method.paramStructTypeId)},`);
      out.push(`    resultStructTypeId: ${formatBigint(method.resultStructTypeId)},`);
      out.push("  },");
    }
  }
  out.push("] as const;");
  out.push("");

  return out.join("\n");
}
