/**
 * Interface/RPC client and server emission functions.
 */

import type { InterfaceMethodModel, NodeModel } from "./model.ts";
import type { InterfaceInfo, StructInfo } from "./emitter_helpers.ts";
import {
  collectLocalInterfaces,
  collectLocalTypes,
  formatBigint,
  quoteIfNeeded,
  toCamelCase,
} from "./emitter_helpers.ts";

interface ResolvedMethodInfo {
  readonly method: InterfaceMethodModel;
  readonly methodName: string;
  readonly params: StructInfo;
  readonly results: StructInfo;
  readonly sourceInterfaceId: bigint;
}

interface ResolvedInterfaceInfo {
  readonly info: InterfaceInfo;
  readonly methods: ResolvedMethodInfo[];
  readonly acceptedInterfaceIds: bigint[];
}

export type RpcResolvedMethodInfo = ResolvedMethodInfo;
export type RpcResolvedInterfaceInfo = ResolvedInterfaceInfo;

export function resolveRpcInterfaces(
  fileNode: NodeModel,
  nodeById: Map<bigint, NodeModel>,
): RpcResolvedInterfaceInfo[] {
  const localTypes = collectLocalTypes(fileNode, nodeById);
  const structById = new Map(
    localTypes.structInfos.map((item) => [item.id, item] as const),
  );
  const interfaces = collectLocalInterfaces(fileNode, nodeById);
  return interfaces.map((info) =>
    resolveInterfaceInfo(info, nodeById, structById)
  );
}

export function emitRpcModule(
  fileNode: NodeModel,
  nodeById: Map<bigint, NodeModel>,
  capnpModulePath: string,
): string {
  const out: string[] = [];
  out.push("// Generated by capnpc-deno");
  out.push("// DO NOT EDIT MANUALLY.");
  out.push("");

  const resolvedInterfaces = resolveRpcInterfaces(fileNode, nodeById);
  if (resolvedInterfaces.length === 0) {
    out.push("export {};");
    out.push("");
    return out.join("\n");
  }

  const sharedRpcTypeNames = [
    "RpcBootstrapClientTransport",
    "RpcCallContext",
    "RpcCallOptions",
    "RpcClientTransport",
    "RpcExportCapabilityOptions",
    "RpcFinishOptions",
    "RpcServerDispatch",
    "RpcServerDispatchResult",
    "RpcServerRegistry",
  ] as const;
  const localSharedRpcTypeNames = sharedRpcTypeNames.filter((name) =>
    name !== "RpcFinishOptions"
  );

  const typeImports = new Set<string>([
    "CapabilityPointer",
    "EncodeWithCapsResult",
    "PreambleCapDescriptor",
    ...localSharedRpcTypeNames,
  ]);
  const valueImports = new Set<string>([
    "encodeStructMessageWithCaps",
    "decodeStructMessageWithCaps",
  ]);

  for (const resolvedInfo of resolvedInterfaces) {
    for (const method of resolvedInfo.methods) {
      typeImports.add(method.params.typeName);
      valueImports.add(method.params.codecConst);
      valueImports.add(method.params.descriptorConst);
      typeImports.add(method.results.typeName);
      valueImports.add(method.results.codecConst);
      valueImports.add(method.results.descriptorConst);
    }
  }

  const sortedTypeImports = [...typeImports].sort((left, right) =>
    left.localeCompare(right)
  );
  const sortedValueImports = [...valueImports].sort((left, right) =>
    left.localeCompare(right)
  );
  out.push(
    `import type { ${sortedTypeImports.join(", ")} } from ${
      JSON.stringify(`./${capnpModulePath}`)
    };`,
  );
  if (sortedValueImports.length > 0) {
    out.push(
      `import { ${sortedValueImports.join(", ")} } from ${
        JSON.stringify(`./${capnpModulePath}`)
      };`,
    );
  }
  out.push("");
  out.push(
    `export type { ${sharedRpcTypeNames.join(", ")} } from ${
      JSON.stringify(`./${capnpModulePath}`)
    };`,
  );
  out.push("");

  emitRpcInterfaceDefinitions(out, resolvedInterfaces);

  return out.join("\n");
}

export function emitRpcInterfaceDefinitions(
  out: string[],
  resolvedInterfaces: RpcResolvedInterfaceInfo[],
): void {
  for (const resolvedInfo of resolvedInterfaces) {
    emitInterfaceCode(out, resolvedInfo);
  }
}

function emitInterfaceCode(
  out: string[],
  resolvedInfo: ResolvedInterfaceInfo,
): void {
  const info = resolvedInfo.info;
  const resolvedMethods = resolvedInfo.methods;

  out.push(
    `export const ${info.typeName}InterfaceId = ${formatBigint(info.id)};`,
  );
  out.push("");
  out.push(`export const ${info.typeName}MethodOrdinals = {`);
  for (const resolved of resolvedMethods) {
    out.push(
      `  ${quoteIfNeeded(resolved.methodName)}: ${resolved.method.codeOrder},`,
    );
  }
  out.push("} as const;");
  out.push("");

  out.push(`export interface ${info.typeName}Client {`);
  for (const resolved of resolvedMethods) {
    out.push(
      `  ${
        quoteIfNeeded(resolved.methodName)
      }(params: ${resolved.params.typeName}, options?: RpcCallOptions): Promise<${resolved.results.typeName}>;`,
    );
  }
  out.push("}");
  out.push("");

  out.push(`export interface ${info.typeName}Server {`);
  for (const resolved of resolvedMethods) {
    out.push(
      `  ${
        quoteIfNeeded(resolved.methodName)
      }(params: ${resolved.params.typeName}, ctx: RpcCallContext): Promise<${resolved.results.typeName}> | ${resolved.results.typeName};`,
    );
  }
  out.push("}");
  out.push("");

  out.push(
    `export function create${info.typeName}Client(transport: RpcClientTransport, capability: CapabilityPointer): ${info.typeName}Client {`,
  );
  out.push("  return {");
  for (const resolved of resolvedMethods) {
    out.push(
      `    ${
        quoteIfNeeded(resolved.methodName)
      }: async (params: ${resolved.params.typeName}, options?: RpcCallOptions): Promise<${resolved.results.typeName}> => {`,
    );
    // Encode params with cap table support (handles capability parameters)
    out.push(
      `      const encoded: EncodeWithCapsResult = encodeStructMessageWithCaps(${resolved.params.descriptorConst}, params);`,
    );
    out.push("      let questionId: number | undefined;");
    out.push(
      "      const callOptions: RpcCallOptions & { paramsCapTable?: PreambleCapDescriptor[] } = {",
    );
    out.push("        ...(options ?? {}),");
    out.push(
      `        interfaceId: options?.interfaceId ?? ${
        formatBigint(resolved.sourceInterfaceId)
      },`,
    );
    out.push("        onQuestionId: (value: number): void => {");
    out.push("          questionId = value;");
    out.push("          options?.onQuestionId?.(value);");
    out.push("        },");
    out.push(
      "        ...(encoded.capTable.length > 0 ? { paramsCapTable: encoded.capTable } : {}),",
    );
    out.push("      };");
    // Use callRaw when available (provides cap table in response)
    out.push("      if (transport.callRaw) {");
    out.push(
      `        const raw = await transport.callRaw(capability, ${info.typeName}MethodOrdinals[${
        JSON.stringify(resolved.methodName)
      }], encoded.content, callOptions);`,
    );
    out.push("        try {");
    out.push(
      `          return decodeStructMessageWithCaps(${resolved.results.descriptorConst}, raw.contentBytes, raw.capTable) as ${resolved.results.typeName};`,
    );
    out.push("        } finally {");
    out.push(
      "          if ((options?.autoFinish ?? true) && questionId !== undefined && transport.finish) {",
    );
    out.push(
      "            await transport.finish(questionId, options?.finish);",
    );
    out.push("          }");
    out.push("        }");
    out.push("      }");
    // Fallback to call() for transports without callRaw
    out.push(
      `      const response = await transport.call(capability, ${info.typeName}MethodOrdinals[${
        JSON.stringify(resolved.methodName)
      }], encoded.content, callOptions);`,
    );
    out.push("      try {");
    out.push(
      `        return decodeStructMessageWithCaps(${resolved.results.descriptorConst}, response, []) as ${resolved.results.typeName};`,
    );
    out.push("      } finally {");
    out.push(
      "        if ((options?.autoFinish ?? true) && questionId !== undefined && transport.finish) {",
    );
    out.push("          await transport.finish(questionId, options?.finish);");
    out.push("        }");
    out.push("      }");
    out.push("    },");
  }
  out.push("  };");
  out.push("}");
  out.push("");
  out.push(`export async function bootstrap${info.typeName}Client(`);
  out.push("  transport: RpcBootstrapClientTransport,");
  out.push("  options?: RpcCallOptions,");
  out.push(`): Promise<${info.typeName}Client> {`);
  out.push("  const capability = await transport.bootstrap(options);");
  out.push(`  return create${info.typeName}Client(transport, capability);`);
  out.push("}");
  out.push("");

  out.push(
    `export function create${info.typeName}Server(server: ${info.typeName}Server): RpcServerDispatch {`,
  );

  const methodsByInterfaceId = new Map<bigint, ResolvedMethodInfo[]>();
  for (const method of resolvedMethods) {
    const list = methodsByInterfaceId.get(method.sourceInterfaceId) ?? [];
    list.push(method);
    methodsByInterfaceId.set(method.sourceInterfaceId, list);
  }

  out.push("  return {");
  out.push(`    interfaceId: ${info.typeName}InterfaceId,`);
  if (resolvedInfo.acceptedInterfaceIds.length > 1) {
    out.push(
      `    interfaceIds: [${
        resolvedInfo.acceptedInterfaceIds.map((id) => formatBigint(id)).join(
          ", ",
        )
      }] as const,`,
    );
  }
  out.push(
    "    dispatch: async (methodId: number, params: Uint8Array, ctx: RpcCallContext): Promise<RpcServerDispatchResult> => {",
  );

  if (resolvedInfo.acceptedInterfaceIds.length > 1) {
    out.push(
      `      const resolvedInterfaceId = ctx.interfaceId ?? ${info.typeName}InterfaceId;`,
    );
    out.push("      switch (resolvedInterfaceId) {");
    for (const interfaceId of resolvedInfo.acceptedInterfaceIds) {
      out.push(`        case ${formatBigint(interfaceId)}: {`);
      emitServerMethodSwitch(
        out,
        methodsByInterfaceId.get(interfaceId) ?? [],
        "          ",
      );
      out.push("        }");
    }
    out.push("        default:");
    out.push(
      '          throw new Error("unknown interface id: " + String(resolvedInterfaceId));',
    );
    out.push("      }");
  } else {
    emitServerMethodSwitch(
      out,
      methodsByInterfaceId.get(info.id) ?? [],
      "      ",
    );
  }

  out.push("    },");
  out.push("  };");
  out.push("}");
  out.push("");
  out.push(`export function register${info.typeName}Server(`);
  out.push("  registry: RpcServerRegistry,");
  out.push(`  server: ${info.typeName}Server,`);
  out.push("  options: RpcExportCapabilityOptions = {},");
  out.push("): CapabilityPointer {");
  out.push(
    `  return registry.exportCapability(create${info.typeName}Server(server), options);`,
  );
  out.push("}");
  out.push("");
}

function sortedInterfaceMethods(node: NodeModel): InterfaceMethodModel[] {
  return node.interfaceNode?.methods
    .slice()
    .sort((a, b) =>
      (a.codeOrder - b.codeOrder) || a.name.localeCompare(b.name)
    ) ??
    [];
}

function collectAncestorInterfaceIds(
  info: InterfaceInfo,
  nodeById: Map<bigint, NodeModel>,
): bigint[] {
  const ancestors: bigint[] = [];
  const seen = new Set<bigint>([info.id]);
  const visiting = new Set<bigint>();

  const walk = (interfaceId: bigint): void => {
    if (visiting.has(interfaceId)) {
      throw new Error(
        `cyclic interface inheritance detected at ${formatBigint(interfaceId)}`,
      );
    }

    visiting.add(interfaceId);
    const node = nodeById.get(interfaceId);
    if (!node || node.kind !== "interface" || !node.interfaceNode) {
      visiting.delete(interfaceId);
      throw new Error(
        `interface ${info.typeName} references unknown superclass id ${
          formatBigint(interfaceId)
        }`,
      );
    }

    const superclasses = node.interfaceNode.superclasses ?? [];
    for (const parentId of superclasses) {
      if (seen.has(parentId)) continue;
      seen.add(parentId);
      walk(parentId);
      ancestors.push(parentId);
    }

    visiting.delete(interfaceId);
  };

  walk(info.id);
  return ancestors;
}

function resolveInterfaceInfo(
  info: InterfaceInfo,
  nodeById: Map<bigint, NodeModel>,
  structById: Map<bigint, StructInfo>,
): ResolvedInterfaceInfo {
  const usedMethodNames = new Set<string>();
  const methods: ResolvedMethodInfo[] = [];
  const acceptedInterfaceIds = [
    info.id,
    ...collectAncestorInterfaceIds(info, nodeById),
  ];

  const addMethod = (
    method: InterfaceMethodModel,
    sourceInterfaceId: bigint,
  ): void => {
    const baseName = toCamelCase(method.name);
    let methodName = baseName;
    let suffix = 2;
    while (usedMethodNames.has(methodName)) {
      methodName = `${baseName}${suffix}`;
      suffix += 1;
    }
    usedMethodNames.add(methodName);

    const params = structById.get(method.paramStructTypeId);
    if (!params) {
      throw new Error(
        `interface ${info.typeName} method ${
          JSON.stringify(method.name)
        } references unknown param struct id ${
          formatBigint(method.paramStructTypeId)
        } (source interface ${formatBigint(sourceInterfaceId)})`,
      );
    }
    const results = structById.get(method.resultStructTypeId);
    if (!results) {
      throw new Error(
        `interface ${info.typeName} method ${
          JSON.stringify(method.name)
        } references unknown result struct id ${
          formatBigint(method.resultStructTypeId)
        } (source interface ${formatBigint(sourceInterfaceId)})`,
      );
    }

    methods.push({
      method,
      methodName,
      params,
      results,
      sourceInterfaceId,
    });
  };

  for (const method of sortedInterfaceMethods(info.node)) {
    addMethod(method, info.id);
  }

  for (const ancestorId of acceptedInterfaceIds.slice(1)) {
    const ancestorNode = nodeById.get(ancestorId);
    if (
      !ancestorNode || ancestorNode.kind !== "interface" ||
      !ancestorNode.interfaceNode
    ) {
      throw new Error(
        `interface ${info.typeName} references unknown superclass id ${
          formatBigint(ancestorId)
        }`,
      );
    }
    for (const method of sortedInterfaceMethods(ancestorNode)) {
      addMethod(method, ancestorId);
    }
  }

  return { info, methods, acceptedInterfaceIds };
}

function emitServerMethodSwitch(
  out: string[],
  methods: ResolvedMethodInfo[],
  indent: string,
): void {
  out.push(`${indent}switch (methodId) {`);
  for (const resolved of methods) {
    out.push(`${indent}  case ${resolved.method.codeOrder}: {`);
    out.push(
      `${indent}    const decoded = decodeStructMessageWithCaps(${resolved.params.descriptorConst}, params, ctx.paramsCapTable ?? []) as ${resolved.params.typeName};`,
    );
    out.push(
      `${indent}    const result = await server[${
        JSON.stringify(resolved.methodName)
      }](decoded, ctx);`,
    );
    out.push(
      `${indent}    const encoded = encodeStructMessageWithCaps(${resolved.results.descriptorConst}, result);`,
    );
    out.push(`${indent}    if (encoded.capTable.length > 0) {`);
    out.push(
      `${indent}      return { content: encoded.content, capTable: encoded.capTable };`,
    );
    out.push(`${indent}    }`);
    out.push(`${indent}    return encoded.content;`);
    out.push(`${indent}  }`);
  }
  out.push(`${indent}  default:`);
  out.push(
    `${indent}    throw new Error("unknown method ordinal: " + methodId);`,
  );
  out.push(`${indent}}`);
}
