/**
 * Monolithic `*_types.ts` emission containing:
 *   - schema/runtime types + codecs,
 *   - RPC helpers + stubs,
 *   - high-level service interface + token adapters.
 */

import type { FieldModel, NodeModel } from "./model.ts";
import {
  collectLocalInterfaces,
  collectLocalTypes,
  quoteIfNeeded,
  simpleNodeName,
  toCamelCase,
  toPascalCase,
} from "./emitter_helpers.ts";
import {
  emitEnum,
  emitStructDescriptor,
  emitStructInterface,
} from "./emitter_types.ts";
import type {
  RpcResolvedInterfaceInfo,
  RpcResolvedMethodInfo,
} from "./emitter_rpc.ts";
import {
  emitRpcInterfaceDefinitions,
  resolveRpcInterfaces,
} from "./emitter_rpc.ts";

type MethodShapeKind = "none" | "single" | "multi";

interface MethodShape {
  paramKind: MethodShapeKind;
  resultKind: MethodShapeKind;
  paramFieldName?: string;
  resultFieldName?: string;
  paramFieldKind?: "interface";
  resultFieldKind?: "interface";
  paramFieldInterfaceId?: bigint;
  resultFieldInterfaceId?: bigint;
}

export function emitTypesModule(
  fileNode: NodeModel,
  nodeById: Map<bigint, NodeModel>,
): string {
  const out: string[] = [];
  out.push("// Generated by capnpc-deno");
  out.push("// DO NOT EDIT MANUALLY.");
  out.push("");
  out.push('export * from "@nullstyle/capnp/encoding";');
  out.push("export type {");
  out.push("  RpcBootstrapClientTransport,");
  out.push("  RpcCallContext,");
  out.push("  RpcCallOptions,");
  out.push("  RpcClientTransport,");
  out.push("  RpcExportCapabilityOptions,");
  out.push("  RpcFinishOptions,");
  out.push("  RpcGeneratedServerDispatch as RpcServerDispatch,");
  out.push("  RpcServerDispatchResult,");
  out.push("  RpcServerRegistry,");
  out.push("  RpcServiceToken,");
  out.push("  RpcStub,");
  out.push('} from "@nullstyle/capnp/rpc";');
  out.push("import type {");
  out.push("  AnyPointerValue,");
  out.push("  CapabilityPointer,");
  out.push("  EncodeWithCapsResult,");
  out.push("  EnumTypeDescriptor,");
  out.push("  PreambleCapDescriptor,");
  out.push("  StructCodec,");
  out.push("  StructDescriptor,");
  out.push('} from "@nullstyle/capnp/encoding";');
  out.push("import type {");
  out.push("  RpcBootstrapClientTransport,");
  out.push("  RpcCallContext,");
  out.push("  RpcCallOptions,");
  out.push("  RpcClientTransport,");
  out.push("  RpcExportCapabilityOptions,");
  out.push("  RpcGeneratedServerDispatch as RpcServerDispatch,");
  out.push("  RpcServerDispatchResult,");
  out.push("  RpcServerRegistry,");
  out.push("  RpcServiceToken,");
  out.push("  RpcStub,");
  out.push('} from "@nullstyle/capnp/rpc";');
  out.push("import {");
  out.push("  decodeStructMessage,");
  out.push("  decodeStructMessageWithCaps,");
  out.push("  encodeStructMessage,");
  out.push("  encodeStructMessageWithCaps,");
  out.push("  TYPE_ANY_POINTER,");
  out.push("  TYPE_BOOL,");
  out.push("  TYPE_DATA,");
  out.push("  TYPE_FLOAT32,");
  out.push("  TYPE_FLOAT64,");
  out.push("  TYPE_INT16,");
  out.push("  TYPE_INT32,");
  out.push("  TYPE_INT64,");
  out.push("  TYPE_INT8,");
  out.push("  TYPE_INTERFACE,");
  out.push("  TYPE_TEXT,");
  out.push("  TYPE_UINT16,");
  out.push("  TYPE_UINT32,");
  out.push("  TYPE_UINT64,");
  out.push("  TYPE_UINT8,");
  out.push("  TYPE_VOID,");
  out.push('} from "@nullstyle/capnp/encoding";');
  out.push("");
  emitCapabilityBridgeHelpers(out);

  const localTypes = collectLocalTypes(fileNode, nodeById);
  const enumInfos = localTypes.enumInfos;
  const structInfos = localTypes.structInfos;
  const enumById = new Map(enumInfos.map((item) => [item.id, item] as const));
  const structById = new Map(
    structInfos.map((item) => [item.id, item] as const),
  );

  for (const enumInfo of enumInfos) {
    emitEnum(out, enumInfo);
  }

  for (const structInfo of structInfos) {
    emitStructInterface(out, structInfo, nodeById, enumById, structById);
  }

  for (const structInfo of structInfos) {
    emitStructDescriptor(out, structInfo, nodeById, enumById, structById);
  }

  const resolvedInterfaces = resolveRpcInterfaces(fileNode, nodeById);
  emitRpcInterfaceDefinitions(out, resolvedInterfaces);

  const localInterfaces = collectLocalInterfaces(fileNode, nodeById);
  const interfaceById = new Map(
    localInterfaces.map((info) => [info.id, info.typeName] as const),
  );

  for (const resolved of resolvedInterfaces) {
    emitHighLevelInterface(out, resolved, interfaceById, nodeById);
    emitClientAdapter(out, resolved, interfaceById, nodeById);
    emitServerAdapter(out, resolved, interfaceById, nodeById);
    emitServiceToken(out, resolved);
  }

  return `${out.join("\n")}\n`;
}

function emitCapabilityBridgeHelpers(out: string[]): void {
  out.push(
    'const RPC_STUB_CAPABILITY = Symbol.for("@nullstyle/capnp/rpcStubCapability");',
  );
  out.push("");
  out.push("interface RpcClientTransportWithCapabilityExport");
  out.push("  extends RpcClientTransport {");
  out.push(
    "  exportCapability?(dispatch: RpcServerDispatch, options?: RpcExportCapabilityOptions): CapabilityPointer;",
  );
  out.push("}");
  out.push("");
  out.push(
    "function parseCapabilityPointer(value: unknown): CapabilityPointer | null {",
  );
  out.push('  if (!value || typeof value !== "object") return null;');
  out.push("  const direct = value as { capabilityIndex?: unknown };");
  out.push(
    '  if (typeof direct.capabilityIndex === "number" && Number.isInteger(direct.capabilityIndex) && direct.capabilityIndex >= 0) {',
  );
  out.push("    return { capabilityIndex: direct.capabilityIndex };");
  out.push("  }");
  out.push(
    "  const tagged = (value as Record<PropertyKey, unknown>)[RPC_STUB_CAPABILITY];",
  );
  out.push('  if (!tagged || typeof tagged !== "object") return null;');
  out.push("  const taggedPointer = tagged as { capabilityIndex?: unknown };");
  out.push(
    '  if (typeof taggedPointer.capabilityIndex === "number" && Number.isInteger(taggedPointer.capabilityIndex) && taggedPointer.capabilityIndex >= 0) {',
  );
  out.push("    return { capabilityIndex: taggedPointer.capabilityIndex };");
  out.push("  }");
  out.push("  return null;");
  out.push("}");
  out.push("");
  out.push(
    "function requireRpcStubCapability(value: unknown): CapabilityPointer {",
  );
  out.push("  const capability = parseCapabilityPointer(value);");
  out.push(
    '  if (!capability) throw new Error("expected RpcStub capability");',
  );
  out.push("  return capability;");
  out.push("}");
  out.push("");
  out.push("function withCapabilityStubLifecycle<TClient extends object>(");
  out.push("  client: TClient,");
  out.push("  capability: CapabilityPointer,");
  out.push("  transport: RpcClientTransport,");
  out.push("): RpcStub<TClient> {");
  out.push("  let closed = false;");
  out.push("  const close = async (): Promise<void> => {");
  out.push("    if (closed) return;");
  out.push("    closed = true;");
  out.push("    await transport.release?.(capability, 1);");
  out.push("  };");
  out.push("  return new Proxy(client as object, {");
  out.push("    get(target, prop, receiver) {");
  out.push('      if (prop === "close") return close;');
  out.push("      if (prop === Symbol.asyncDispose) return close;");
  out.push("      if (prop === Symbol.dispose) {");
  out.push("        return (): void => {");
  out.push("          void close();");
  out.push("        };");
  out.push("      }");
  out.push("      if (prop === RPC_STUB_CAPABILITY) return capability;");
  out.push("      return Reflect.get(target, prop, receiver);");
  out.push("    },");
  out.push("  }) as RpcStub<TClient>;");
  out.push("}");
  out.push("");
  out.push("function capabilityToServiceStub<TClient extends object>(");
  out.push("  value: unknown,");
  out.push("  transport: RpcClientTransport,");
  out.push(
    "  createClient: (transport: RpcClientTransport, capability: CapabilityPointer) => TClient,",
  );
  out.push("): RpcStub<TClient> {");
  out.push("  const capability = requireRpcStubCapability(value);");
  out.push(
    "  return withCapabilityStubLifecycle(createClient(transport, capability), capability, transport);",
  );
  out.push("}");
  out.push("");
  out.push(
    "function requireOutboundClient(ctx: RpcCallContext): RpcClientTransport {",
  );
  out.push("  if (!ctx.outboundClient) {");
  out.push(
    '    throw new Error("rpc outbound client is unavailable for capability callbacks");',
  );
  out.push("  }");
  out.push("  return ctx.outboundClient;");
  out.push("}");
  out.push("");
  out.push(
    "function exportCapabilityFromTransport<TClient extends object, TServer extends object>(",
  );
  out.push("  transport: RpcClientTransport,");
  out.push("  service: RpcServiceToken<TClient, TServer>,");
  out.push("  value: TServer | RpcStub<TClient>,");
  out.push("): CapabilityPointer {");
  out.push("  const existing = parseCapabilityPointer(value);");
  out.push("  if (existing) return existing;");
  out.push(
    "  const host = transport as RpcClientTransportWithCapabilityExport;",
  );
  out.push("  const exportCapability = host.exportCapability;");
  out.push("  if (!exportCapability) {");
  out.push(
    '    throw new Error("transport does not support exporting local capabilities");',
  );
  out.push("  }");
  out.push("  return service.registerServer(");
  out.push("    {");
  out.push("      exportCapability: (dispatch, options) =>");
  out.push("        exportCapability.call(host, dispatch, options),");
  out.push("    },");
  out.push("    value as TServer,");
  out.push("    { referenceCount: 1 },");
  out.push("  );");
  out.push("}");
  out.push("");
  out.push(
    "function exportCapabilityFromContext<TClient extends object, TServer extends object>(",
  );
  out.push("  ctx: RpcCallContext,");
  out.push("  service: RpcServiceToken<TClient, TServer>,");
  out.push("  value: TServer | RpcStub<TClient>,");
  out.push("): CapabilityPointer {");
  out.push("  const existing = parseCapabilityPointer(value);");
  out.push("  if (existing) return existing;");
  out.push("  if (!ctx.exportCapability) {");
  out.push(
    '    throw new Error("rpc call context does not support exporting local capabilities");',
  );
  out.push("  }");
  out.push("  return service.registerServer(");
  out.push("    { exportCapability: ctx.exportCapability },");
  out.push("    value as TServer,");
  out.push("    { referenceCount: 1 },");
  out.push("  );");
  out.push("}");
  out.push("");
}

function emitHighLevelInterface(
  out: string[],
  resolved: RpcResolvedInterfaceInfo,
  interfaceById: Map<bigint, string>,
  nodeById: Map<bigint, NodeModel>,
): void {
  const typeName = resolved.info.typeName;
  out.push(`export interface ${typeName} {`);
  for (const method of resolved.methods) {
    const shape = methodShape(method);
    const signature = emitMethodSignature(
      method,
      shape,
      interfaceById,
      nodeById,
    );
    out.push(`  ${signature}`);
  }
  out.push("}");
  out.push("");
}

function emitMethodSignature(
  method: RpcResolvedMethodInfo,
  shape: MethodShape,
  interfaceById: Map<bigint, string>,
  nodeById: Map<bigint, NodeModel>,
): string {
  const methodName = quoteIfNeeded(method.methodName);
  const optionsArg = "options?: RpcCallOptions";
  const paramArg = (() => {
    switch (shape.paramKind) {
      case "none":
        return optionsArg;
      case "single": {
        const fieldType = singleFieldTypeExpression(
          shape.paramFieldName!,
          shape.paramFieldKind,
          method.params.typeName,
          "param",
          method,
          interfaceById,
          nodeById,
        );
        return `value: ${fieldType}, ${optionsArg}`;
      }
      case "multi":
        return `params: ${method.params.typeName}, ${optionsArg}`;
    }
  })();

  const returnType = (() => {
    switch (shape.resultKind) {
      case "none":
        return "Promise<void>";
      case "single": {
        const fieldType = singleFieldTypeExpression(
          shape.resultFieldName!,
          shape.resultFieldKind,
          method.results.typeName,
          "result",
          method,
          interfaceById,
          nodeById,
        );
        return `Promise<${fieldType}>`;
      }
      case "multi":
        return `Promise<${method.results.typeName}>`;
    }
  })();

  return `${methodName}(${paramArg}): ${returnType};`;
}

function emitClientAdapter(
  out: string[],
  resolved: RpcResolvedInterfaceInfo,
  interfaceById: Map<bigint, string>,
  nodeById: Map<bigint, NodeModel>,
): void {
  const typeName = resolved.info.typeName;
  out.push(`function create${typeName}ServiceClient(`);
  out.push(`  client: ${typeName}Client,`);
  out.push("  transport: RpcClientTransport,");
  out.push(`): ${typeName} {`);
  out.push("  return {");
  for (const method of resolved.methods) {
    const methodName = quoteIfNeeded(method.methodName);
    const methodAccess = accessProperty("client", method.methodName);
    const shape = methodShape(method);
    const singleParamType = shape.paramKind === "single"
      ? singleFieldTypeExpression(
        shape.paramFieldName!,
        shape.paramFieldKind,
        method.params.typeName,
        "param",
        method,
        interfaceById,
        nodeById,
      )
      : null;
    const argList = (() => {
      switch (shape.paramKind) {
        case "none":
          return "options?: RpcCallOptions";
        case "single":
          return `value: ${singleParamType}, options?: RpcCallOptions`;
        case "multi":
          return `params: ${method.params.typeName}, options?: RpcCallOptions`;
      }
    })();
    out.push(`    ${methodName}: async (${argList}) => {`);
    out.push(
      `      const result = await ${methodAccess}(${
        emitClientParamConstruction(
          method,
          shape,
          interfaceById,
        )
      }, options);`,
    );
    const resultEmit = emitClientResultExtraction(
      method,
      shape,
      interfaceById,
    );
    if (resultEmit.length > 0) {
      out.push(`      ${resultEmit}`);
    }
    out.push("    },");
  }
  out.push("  };");
  out.push("}");
  out.push("");
}

function emitServerAdapter(
  out: string[],
  resolved: RpcResolvedInterfaceInfo,
  interfaceById: Map<bigint, string>,
  nodeById: Map<bigint, NodeModel>,
): void {
  const typeName = resolved.info.typeName;
  out.push(`function create${typeName}ServiceServer(`);
  out.push(`  server: ${typeName},`);
  out.push(`): ${typeName}Server {`);
  out.push("  return {");
  for (const method of resolved.methods) {
    const methodName = quoteIfNeeded(method.methodName);
    const methodAccess = accessProperty("server", method.methodName);
    const shape = methodShape(method);
    out.push(
      `    ${methodName}: async (params: ${method.params.typeName}, _ctx: RpcCallContext) => {`,
    );
    out.push(
      `      const result = await ${methodAccess}(${
        emitServerParamExtraction(
          method,
          shape,
          interfaceById,
          nodeById,
        )
      });`,
    );
    out.push(
      `      ${
        emitServerResultConstruction(
          method,
          shape,
          interfaceById,
        )
      }`,
    );
    out.push("    },");
  }
  out.push("  };");
  out.push("}");
  out.push("");
}

function emitServiceToken(
  out: string[],
  resolved: RpcResolvedInterfaceInfo,
): void {
  const typeName = resolved.info.typeName;
  out.push(
    `export const ${typeName}: RpcServiceToken<${typeName}> = Object.freeze({`,
  );
  out.push(`  interfaceId: ${typeName}InterfaceId,`);
  out.push(`  interfaceName: ${JSON.stringify(typeName)},`);
  out.push(
    "  bootstrapClient: async (transport: RpcBootstrapClientTransport, options?: RpcCallOptions) =>",
  );
  out.push(
    `    create${typeName}ServiceClient(await bootstrap${typeName}Client(transport, options), transport),`,
  );
  out.push(
    `  registerServer: (registry: RpcServerRegistry, server: ${typeName}, options?: RpcExportCapabilityOptions) =>`,
  );
  out.push(
    `    register${typeName}Server(registry, create${typeName}ServiceServer(server), options),`,
  );
  out.push("});");
  out.push("");
}

function methodShape(method: RpcResolvedMethodInfo): MethodShape {
  const params = structFields(method.params.node);
  const results = structFields(method.results.node);
  const paramField = params[0];
  const resultField = results[0];
  const paramFieldInterfaceId =
    interfaceTypeIdFromSingleField(method.params.node) ??
      undefined;
  const resultFieldInterfaceId = interfaceTypeIdFromSingleField(
    method.results.node,
  ) ??
    undefined;
  return {
    paramKind: fieldsKind(params.length),
    resultKind: fieldsKind(results.length),
    paramFieldName: paramField ? toCamelCase(paramField.name) : undefined,
    resultFieldName: resultField ? toCamelCase(resultField.name) : undefined,
    paramFieldKind: paramField?.slot?.type.kind === "interface"
      ? "interface"
      : undefined,
    resultFieldKind: resultField?.slot?.type.kind === "interface"
      ? "interface"
      : undefined,
    paramFieldInterfaceId,
    resultFieldInterfaceId,
  };
}

function fieldsKind(count: number): MethodShapeKind {
  if (count <= 0) return "none";
  if (count === 1) return "single";
  return "multi";
}

function structFields(node: NodeModel): FieldModel[] {
  const structNode = node.structNode;
  if (!structNode) return [];
  return structNode.fields
    .slice()
    .sort((left, right) => left.codeOrder - right.codeOrder)
    .filter((field) => field.slot !== undefined || field.group !== undefined);
}

function singleFieldTypeExpression(
  fieldName: string,
  fieldKind: "interface" | undefined,
  structTypeName: string,
  position: "param" | "result",
  method: RpcResolvedMethodInfo,
  interfaceById: Map<bigint, string>,
  nodeById: Map<bigint, NodeModel>,
): string {
  if (fieldKind === "interface") {
    const fieldTypeId = interfaceTypeIdFromSingleField(
      position === "param" ? method.params.node : method.results.node,
    );
    if (fieldTypeId === null) return "unknown";
    const interfaceName = resolveInterfaceTypeName(
      fieldTypeId,
      interfaceById,
      nodeById,
    );
    if (position === "param") {
      return `${interfaceName} | RpcStub<${interfaceName}>`;
    }
    return `RpcStub<${interfaceName}>`;
  }
  return `${structTypeName}[${JSON.stringify(fieldName)}]`;
}

function interfaceTypeIdFromSingleField(node: NodeModel): bigint | null {
  const fields = structFields(node);
  if (fields.length !== 1) return null;
  const only = fields[0];
  if (!only.slot || only.slot.type.kind !== "interface") return null;
  return only.slot.type.typeId;
}

function resolveInterfaceTypeName(
  typeId: bigint,
  interfaceById: Map<bigint, string>,
  nodeById: Map<bigint, NodeModel>,
): string {
  const local = interfaceById.get(typeId);
  if (local) return local;
  const node = nodeById.get(typeId);
  if (!node) return "unknown";
  return toPascalCase(simpleNodeName(node));
}

function resolveLocalInterfaceTokenName(
  typeId: bigint | undefined,
  interfaceById: Map<bigint, string>,
): string | null {
  if (typeId === undefined) return null;
  return interfaceById.get(typeId) ?? null;
}

function emitClientParamConstruction(
  method: RpcResolvedMethodInfo,
  shape: MethodShape,
  interfaceById: Map<bigint, string>,
): string {
  switch (shape.paramKind) {
    case "none":
      return `{} as ${method.params.typeName}`;
    case "single": {
      if (shape.paramFieldKind === "interface") {
        const tokenName = resolveLocalInterfaceTokenName(
          shape.paramFieldInterfaceId,
          interfaceById,
        );
        if (tokenName) {
          return `{ ${
            quoteIfNeeded(shape.paramFieldName!)
          }: exportCapabilityFromTransport(transport, ${tokenName}, value) }`;
        }
        return `{ ${
          quoteIfNeeded(shape.paramFieldName!)
        }: requireRpcStubCapability(value) }`;
      }
      return `{ ${quoteIfNeeded(shape.paramFieldName!)}: value }`;
    }
    case "multi":
      return "params";
  }
}

function emitClientResultExtraction(
  method: RpcResolvedMethodInfo,
  shape: MethodShape,
  interfaceById: Map<bigint, string>,
): string {
  switch (shape.resultKind) {
    case "none":
      return "return;";
    case "single": {
      if (shape.resultFieldKind === "interface") {
        const tokenName = resolveLocalInterfaceTokenName(
          shape.resultFieldInterfaceId,
          interfaceById,
        );
        if (!tokenName) {
          return `throw new Error("cannot decode non-local capability result for method ${method.methodName}");`;
        }
        return `return capabilityToServiceStub(${
          accessProperty("result", shape.resultFieldName!)
        }, transport, (nextTransport, nextCapability) => create${tokenName}ServiceClient(create${tokenName}Client(nextTransport, nextCapability), nextTransport));`;
      }
      return `return ${accessProperty("result", shape.resultFieldName!)};`;
    }
    case "multi":
      return "return result;";
  }
}

function emitServerParamExtraction(
  method: RpcResolvedMethodInfo,
  shape: MethodShape,
  interfaceById: Map<bigint, string>,
  nodeById: Map<bigint, NodeModel>,
): string {
  switch (shape.paramKind) {
    case "none":
      return "";
    case "single": {
      if (shape.paramFieldKind === "interface") {
        const tokenName = resolveLocalInterfaceTokenName(
          shape.paramFieldInterfaceId,
          interfaceById,
        );
        if (!tokenName) {
          return `requireRpcStubCapability(${
            accessProperty("params", shape.paramFieldName!)
          } as unknown) as unknown as ${
            singleFieldTypeExpression(
              shape.paramFieldName!,
              shape.paramFieldKind,
              method.params.typeName,
              "param",
              method,
              interfaceById,
              nodeById,
            )
          }`;
        }
        return `capabilityToServiceStub(${
          accessProperty("params", shape.paramFieldName!)
        }, requireOutboundClient(_ctx), (nextTransport, nextCapability) => create${tokenName}ServiceClient(create${tokenName}Client(nextTransport, nextCapability), nextTransport))`;
      }
      return `${accessProperty("params", shape.paramFieldName!)}`;
    }
    case "multi":
      return "params";
  }
}

function emitServerResultConstruction(
  method: RpcResolvedMethodInfo,
  shape: MethodShape,
  interfaceById: Map<bigint, string>,
): string {
  switch (shape.resultKind) {
    case "none":
      return `return {} as ${method.results.typeName};`;
    case "single": {
      if (shape.resultFieldKind === "interface") {
        const tokenName = resolveLocalInterfaceTokenName(
          shape.resultFieldInterfaceId,
          interfaceById,
        );
        if (tokenName) {
          return `return { ${
            quoteIfNeeded(shape.resultFieldName!)
          }: exportCapabilityFromContext(_ctx, ${tokenName}, result) };`;
        }
        return `return { ${
          quoteIfNeeded(shape.resultFieldName!)
        }: requireRpcStubCapability(result as unknown) };`;
      }
      return `return { ${quoteIfNeeded(shape.resultFieldName!)}: result };`;
    }
    case "multi":
      return "return result;";
  }
}

function accessProperty(target: string, property: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(property)
    ? `${target}.${property}`
    : `${target}[${JSON.stringify(property)}]`;
}
