/**
 * Thin orchestrator that delegates to focused sub-modules.
 *
 * Public API surface (re-exported unchanged):
 *   - GeneratedFile          (interface)
 *   - generateTypescriptFiles
 *   - renderSingleFileForTest
 *   - renderedFieldNamesForTest
 */

import type {
  CodeGeneratorRequestModel,
  FieldModel,
  NodeModel,
} from "./model.ts";

import { RUNTIME_PREAMBLE } from "./emitter_preamble.ts";
import {
  collectLocalTypes,
  toCamelCase,
  toOutputPath,
} from "./emitter_helpers.ts";
import {
  emitEnum,
  emitStructDescriptor,
  emitStructInterface,
} from "./emitter_types.ts";
import { emitRpcModule } from "./emitter_rpc.ts";
import { emitMetaModule } from "./emitter_meta.ts";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface GeneratedFile {
  path: string;
  contents: string;
  sourceFilename?: string;
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

export function generateTypescriptFiles(
  request: CodeGeneratorRequestModel,
): GeneratedFile[] {
  const nodeById = new Map<bigint, NodeModel>();
  for (const node of request.nodes) {
    nodeById.set(node.id, node);
  }

  const files: GeneratedFile[] = [];
  for (const requested of request.requestedFiles) {
    const fileNode = nodeById.get(requested.id);
    if (!fileNode || fileNode.kind !== "file") continue;

    const capnpPath = toOutputPath(requested.filename, "capnp");
    const capnpContents = emitCapnpModule(fileNode, nodeById);
    files.push({
      path: capnpPath,
      contents: capnpContents,
      sourceFilename: requested.filename,
    });

    const rpcPath = toOutputPath(requested.filename, "rpc");
    const rpcContents = emitRpcModule(fileNode, nodeById, capnpPath);
    files.push({
      path: rpcPath,
      contents: rpcContents,
      sourceFilename: requested.filename,
    });

    const metaPath = toOutputPath(requested.filename, "meta");
    const metaContents = emitMetaModule(requested, fileNode, nodeById);
    files.push({
      path: metaPath,
      contents: metaContents,
      sourceFilename: requested.filename,
    });
  }
  return files;
}

// ---------------------------------------------------------------------------
// Capnp module assembly (composes preamble + types)
// ---------------------------------------------------------------------------

function emitCapnpModule(
  fileNode: NodeModel,
  nodeById: Map<bigint, NodeModel>,
): string {
  const out: string[] = [];
  out.push("// Generated by capnpc-deno");
  out.push("// DO NOT EDIT MANUALLY.");
  out.push("");
  out.push(RUNTIME_PREAMBLE.trimEnd());
  out.push("");

  const localTypes = collectLocalTypes(fileNode, nodeById);
  const enumInfos = localTypes.enumInfos;
  const structInfos = localTypes.structInfos;
  const enumById = new Map(enumInfos.map((item) => [item.id, item] as const));
  const structById = new Map(structInfos.map((item) => [item.id, item] as const));

  for (const enumInfo of enumInfos) {
    emitEnum(out, enumInfo);
  }

  for (const structInfo of structInfos) {
    emitStructInterface(out, structInfo, nodeById, enumById, structById);
  }

  for (const structInfo of structInfos) {
    emitStructDescriptor(out, structInfo, nodeById, enumById, structById);
  }

  return `${out.join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

export function renderSingleFileForTest(
  request: CodeGeneratorRequestModel,
): string {
  const capnpFiles = generateTypescriptFiles(request).filter((file) =>
    file.path.endsWith("_capnp.ts")
  );
  if (capnpFiles.length !== 1) {
    throw new Error(`expected exactly one generated capnp file, got ${capnpFiles.length}`);
  }
  return capnpFiles[0].contents;
}

export function renderedFieldNamesForTest(fields: FieldModel[]): string[] {
  return fields
    .slice()
    .sort((a, b) => a.codeOrder - b.codeOrder)
    .filter((field) => field.slot !== undefined)
    .map((field) => toCamelCase(field.name));
}
