set shell := ["bash", "-cu"]

default:
    @just --list

# Run examples

run-getting-started:
    deno run getting-started/getting-started.ts

run-tcp-golden-path:
    deno run --allow-net=127.0.0.1 tcp_golden_path/tcp_golden_path.ts

run-tcp-golden-server hostname="127.0.0.1" port="4000":
    deno run --allow-net tcp_golden_path/tcp_golden_path_server.ts {{ hostname }} {{ port }}

run-tcp-golden-client hostname="127.0.0.1" port="4000":
    deno run --allow-net tcp_golden_path/tcp_golden_path_client.ts {{ hostname }} {{ port }}

run-tcp-echo-server hostname="127.0.0.1" port="4000":
    deno run --allow-net tcp_echo_server/tcp_echo_server.ts {{ hostname }} {{ port }}

run-tcp-echo-client hostname="127.0.0.1" port="4000":
    deno run --allow-net tcp_echo_server/tcp_echo_server_client.ts {{ hostname }} {{ port }}

run-bidirectional-capability:
    deno run bidirectional_capability/bidirectional_capability.ts

run-warmup-stats:
    deno run warmup_stats_example/warmup_stats_example.ts

run-smoke-real-wasm:
    deno run --allow-read smoke_real_wasm/smoke_real_wasm.ts

run-ping-ws-server host="127.0.0.1" port="4001" path="/rpc" api_path="/api" protocol="capnp-rpc":
    deno run --allow-net ping/server_ws.ts {{ host }} {{ port }} {{ path }} {{ api_path }} {{ protocol }}

run-ping-ws-client url="ws://127.0.0.1:4001/rpc" protocol="capnp-rpc" count="3":
    deno run --allow-net ping/client_ws.ts {{ url }} {{ protocol }} {{ count }}

run-webtransport-p2p-a:
    deno run --unstable-net --allow-net=127.0.0.1 webtransport_p2p/peer.ts --name alice --port 4443

run-webtransport-p2p-b:
    deno run --unstable-net --allow-net=127.0.0.1 webtransport_p2p/peer.ts --name bob --port 4444 --connect https://127.0.0.1:4443/p2p

run-kvstore-stress-2 host="127.0.0.1" port="9000" key_space="16384" active_keys="1024" concurrency="32" min_batch="8" max_batch="64" duration_seconds="0":
    deno run --allow-net --allow-sys kvstore_stress_2/kvstore_stress_client.ts \
        --host={{ host }} \
        --port={{ port }} \
        --key-space={{ key_space }} \
        --active-keys={{ active_keys }} \
        --concurrency={{ concurrency }} \
        --min-batch={{ min_batch }} \
        --max-batch={{ max_batch }} \
        --duration-seconds={{ duration_seconds }}

# Generate RPC stubs for schema-driven examples

gen-getting-started:
    mkdir -p getting-started/gen
    cd getting-started && capnp compile -odeno:./gen getting-started.capnp

gen-tcp-golden-path:
    rm -rf tcp_golden_path/generated
    mkdir -p tcp_golden_path/generated
    PATH="$HOME/.bin:$PATH" capnp compile -I .. -odeno:tcp_golden_path/generated tcp_golden_path/tcp_golden_path.capnp

gen-tcp-echo-server:
    rm -rf tcp_echo_server/generated
    mkdir -p tcp_echo_server/generated
    PATH="$HOME/.bin:$PATH" capnp compile -I .. -odeno:tcp_echo_server/generated tcp_echo_server/tcp_echo_server.capnp

gen-kvstore-stress-2:
    rm -rf kvstore_stress_2/gen
    mkdir -p kvstore_stress_2/gen
    deno task codegen --schema kvstore_stress_2/kvstore.capnp --out kvstore_stress_2/gen --layout flat

gen-webtransport-p2p:
    rm -rf webtransport_p2p/gen
    mkdir -p webtransport_p2p/gen
    deno task codegen --schema webtransport_p2p/schema.capnp --out webtransport_p2p/gen --layout flat

gen-rpc:
    just gen-getting-started
    just gen-tcp-golden-path
    just gen-tcp-echo-server
    just gen-kvstore-stress-2
    just gen-webtransport-p2p
