const std = @import("std");
const capnpc = @import("capnpc-zig-core");
const fixture_tool = @import("rpc-fixture-tool");

const protocol = capnpc.rpc.protocol;

fn printArray(writer: *std.Io.Writer, name: []const u8, bytes: []const u8) !void {
    try writer.print("export const {s} = new Uint8Array([", .{name});
    for (bytes, 0..) |b, i| {
        if (i != 0) try writer.writeAll(", ");
        try writer.print("0x{x:0>2}", .{b});
    }
    try writer.writeAll("]);\n");
}

fn printCase(
    writer: *std.Io.Writer,
    prefix: []const u8,
    inbound: []const u8,
    outbound: []const u8,
) !void {
    var in_buf: [128]u8 = undefined;
    var out_buf: [128]u8 = undefined;
    const in_name = try std.fmt.bufPrint(&in_buf, "{s}_INBOUND", .{prefix});
    const out_name = try std.fmt.bufPrint(&out_buf, "{s}_OUTBOUND", .{prefix});
    try printArray(writer, in_name, inbound);
    try printArray(writer, out_name, outbound);
    try writer.writeAll("\n");
}

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;

    var stdout_buf: [4096]u8 = undefined;
    var stdout = std.Io.File.stdout().writer(io, &stdout_buf);
    const writer = &stdout.interface;

    var bootstrap_builder = protocol.MessageBuilder.init(allocator);
    defer bootstrap_builder.deinit();
    try bootstrap_builder.buildBootstrap(1);
    const bootstrap_inbound = try bootstrap_builder.finish();
    defer allocator.free(bootstrap_inbound);
    const bootstrap_outbound = try fixture_tool.runCase(allocator, bootstrap_inbound, false);
    defer allocator.free(bootstrap_outbound);
    const bootstrap_success_outbound = try fixture_tool.runCase(allocator, bootstrap_inbound, true);
    defer allocator.free(bootstrap_success_outbound);

    var call_builder = protocol.MessageBuilder.init(allocator);
    defer call_builder.deinit();
    var call = try call_builder.beginCall(2, 0x1234, 9);
    try call.setTargetImportedCap(77);
    _ = try call.initCapTableTyped(0);
    const call_inbound = try call_builder.finish();
    defer allocator.free(call_inbound);
    const call_outbound = try fixture_tool.runCase(allocator, call_inbound, false);
    defer allocator.free(call_outbound);

    var call_bootstrap = try fixture_tool.makeCallToBootstrapFixture(allocator);
    defer call_bootstrap.deinit(allocator);

    try writer.writeAll("// Generated by `just regen-rpc-fixtures`\n");
    try printCase(writer, "BOOTSTRAP_Q1", bootstrap_inbound, bootstrap_outbound);
    try printCase(writer, "BOOTSTRAP_Q1_SUCCESS", bootstrap_inbound, bootstrap_success_outbound);
    try printCase(writer, "CALL_UNKNOWN_CAP_Q2", call_inbound, call_outbound);
    try printCase(writer, "CALL_BOOTSTRAP_CAP_Q2", call_bootstrap.inbound, call_bootstrap.outbound);

    try writer.flush();
}
