import { basename, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { readCompilerPin } from "../tools/compiler_artifact.ts";
import { sha256 } from "../tools/runtime_artifact.ts";
import { CapnpReader } from "../tools/capnpc-deno/capnp_reader.ts";

const root = fileURLToPath(new URL("../", import.meta.url));
const source = resolve(
  Deno.args[0] ??
    join(
      root,
      "dist",
      Deno.build.os === "windows" ? "capnpc-deno.exe" : "capnpc-deno",
    ),
);
const bytes = await Deno.readFile(source);
const receipt = JSON.parse(
  await Deno.readTextFile(`${source}.provenance.json`),
);
if (
  receipt.format !== 1 || receipt.target !== Deno.build.target ||
  receipt.artifact.filename !== basename(source) ||
  receipt.artifact.bytes !== bytes.length ||
  receipt.artifact.sha256 !== await sha256(bytes) ||
  JSON.stringify(receipt.compilerToolchain) !==
    JSON.stringify(await readCompilerPin())
) {
  throw new Error(
    "compiler binary receipt does not match this host or pinned toolchain",
  );
}
const temporary = await Deno.makeTempDir({
  prefix: "capnp standalone consumer ",
});
const binary = join(
  temporary,
  Deno.build.os === "windows"
    ? "compiler with spaces.exe"
    : "compiler with spaces",
);
async function run(
  args: string[],
  input?: Uint8Array,
): Promise<Deno.CommandOutput> {
  const child = new Deno.Command(binary, {
    args,
    cwd: temporary,
    env: {
      DENO_DIR: join(temporary, "empty cache"),
      PATH: "",
      DENO_NO_UPDATE_CHECK: "1",
    },
    stdin: input ? "piped" : "null",
    stdout: "piped",
    stderr: "piped",
  }).spawn();
  let timedOut = false;
  const timeout = setTimeout(() => {
    timedOut = true;
    try {
      child.kill("SIGKILL");
    } catch { /* exited */ }
  }, 30_000);
  try {
    if (input) {
      const writer = child.stdin.getWriter();
      await writer.write(input);
      await writer.close();
    }
    const result = await child.output();
    if (!result.success || timedOut) {
      throw new Error(
        `standalone compiler failed: ${
          timedOut ? "timeout" : new TextDecoder().decode(result.stderr)
        }`,
      );
    }
    return result;
  } finally {
    clearTimeout(timeout);
  }
}
try {
  await Deno.copyFile(source, binary);
  if (Deno.build.os !== "windows") await Deno.chmod(binary, 0o755);
  await Deno.mkdir(join(temporary, "schemas", "types"), { recursive: true });
  await Deno.writeTextFile(
    join(temporary, "schemas", "types", "common.capnp"),
    "@0xb971b22895411843; struct Thing { value @0 :Text; }",
  );
  await Deno.writeFile(
    join(temporary, "schemas", "payload.bin"),
    new Uint8Array([0, 255, 1, 128]),
  );
  await Deno.writeTextFile(
    join(temporary, "schemas", "main.capnp"),
    `@0xec889418ca24f5a1;
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("standalone");
using Base = import "types/common.capnp";
struct Note { item @0 :Base.Thing; payload @1 :Data = embed "payload.bin"; }
`,
  );
  await run([
    "generate",
    "--no-config",
    "--quiet",
    "--schema",
    "schemas/main.capnp",
    "--schema",
    "schemas/types/common.capnp",
    "--out",
    "generated with spaces",
  ]);
  const generated = await Deno.readTextFile(
    join(temporary, "generated with spaces", "schemas", "main_types.ts"),
  );
  if (!generated.includes("interface Note")) {
    throw new Error("standalone schema generation did not produce Note");
  }
  const request = Uint8Array.from(
    atob(
      (await Deno.readTextFile(
        join(root, "tests/fixtures/codegen_requests/multi_schema_request.b64"),
      )).trim(),
    ),
    (char) => char.charCodeAt(0),
  );
  const response = await run(
    ["--no-config", "--plugin-response", "--quiet"],
    request,
  );
  const files = new CapnpReader(response.stdout).root().readStructList(0);
  if (
    !files || files.len() < 2 ||
    !files.get(0).readText(1)?.startsWith("// Generated by capnpc-deno")
  ) throw new Error("standalone stdin plugin response is invalid");
  console.log(
    "Standalone compiler: native execution, empty PATH/cache, spaces, imports, embed, and binary stdin passed",
  );
} finally {
  await Deno.remove(temporary, { recursive: true });
}
