# .github/workflows/ci.yml
name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Installs mise, then runs `mise install` (installs everything in your repo's mise.toml)
      - uses: jdx/mise-action@v3
        with:
          install: true          # default: true
          cache: true            # default: true
          github_token: ${{ github.token }} # helps avoid GitHub API rate limits during installs

      - run: |
        just ci
