import {
  type InteropContainer,
  InteropContainerCodec,
  type InteropGrouped,
  InteropGroupedCodec,
  type InteropHolder,
  InteropHolderCodec,
  type InteropLists,
  InteropListsCodec,
  type InteropPerson,
  InteropPersonCodec,
  type InteropUnion,
  InteropUnionCodec,
  type PingParams,
  PingParamsCodec,
} from "../fixtures/generated/interop_matrix/mod.ts";
import {
  assert,
  assertBytes,
  assertEquals,
  assertThrows,
} from "../test_utils.ts";

const WORD_BYTES = 8;

interface CanonicalCase<T extends object> {
  readonly name: string;
  readonly codec: {
    encode(value: T): Uint8Array;
    decode(bytes: Uint8Array): T;
  };
  readonly value: T;
  readonly hex: string;
  readonly expectEncode?: boolean;
}

function bytesFromHex(hex: string): Uint8Array {
  assert(hex.length % 2 === 0, "hex string must have an even length");
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i += 1) {
    out[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function splitSegments(message: Uint8Array): Uint8Array[] {
  const view = new DataView(
    message.buffer,
    message.byteOffset,
    message.byteLength,
  );
  const segmentCount = view.getUint32(0, true) + 1;
  const headerWords = 1 + segmentCount + (segmentCount % 2 === 0 ? 1 : 0);
  const headerBytes = headerWords * 4;
  const segments: Uint8Array[] = [];
  let cursor = headerBytes;
  for (let i = 0; i < segmentCount; i += 1) {
    const sizeWords = view.getUint32(4 + i * 4, true);
    const sizeBytes = sizeWords * WORD_BYTES;
    segments.push(message.subarray(cursor, cursor + sizeBytes));
    cursor += sizeBytes;
  }
  return segments;
}

function buildMessage(segments: Uint8Array[]): Uint8Array {
  const segmentCount = segments.length;
  const headerWords = 1 + segmentCount + (segmentCount % 2 === 0 ? 1 : 0);
  const headerBytes = headerWords * 4;
  const bodyBytes = segments.reduce(
    (sum, segment) => sum + segment.byteLength,
    0,
  );
  const out = new Uint8Array(headerBytes + bodyBytes);
  const view = new DataView(out.buffer);
  view.setUint32(0, segmentCount - 1, true);
  for (let i = 0; i < segmentCount; i += 1) {
    view.setUint32(4 + i * 4, segments[i].byteLength / WORD_BYTES, true);
  }
  let cursor = headerBytes;
  for (const segment of segments) {
    out.set(segment, cursor);
    cursor += segment.byteLength;
  }
  return out;
}

function farPointerWord(
  targetSegmentId: number,
  landingPadWord: number,
): bigint {
  return 0x2n |
    (BigInt(landingPadWord & 0x1fff_ffff) << 3n) |
    (BigInt(targetSegmentId >>> 0) << 32n);
}

function setWord(segment: Uint8Array, wordIndex: number, value: bigint): void {
  new DataView(segment.buffer, segment.byteOffset, segment.byteLength)
    .setBigUint64(wordIndex * WORD_BYTES, value, true);
}

function toSingleFarRoot(message: Uint8Array): Uint8Array {
  const segments = splitSegments(message);
  assertEquals(segments.length, 1);
  const segment0 = new Uint8Array(WORD_BYTES);
  const segment1 = new Uint8Array(segments[0]);
  setWord(segment0, 0, farPointerWord(1, 0));
  return buildMessage([segment0, segment1]);
}

function assertStableEncoding<T extends object>(
  fixture: CanonicalCase<T>,
): void {
  const expected = bytesFromHex(fixture.hex);
  if (fixture.expectEncode !== false) {
    const encoded = fixture.codec.encode(fixture.value);
    assertBytes(encoded, [...expected], `${fixture.name} canonical encoding`);
  }

  const decoded = fixture.codec.decode(expected);
  if (fixture.expectEncode !== false) {
    const reencoded = fixture.codec.encode(decoded);
    assertBytes(
      reencoded,
      [...expected],
      `${fixture.name} re-encode stability`,
    );
  }
}

const personValue: InteropPerson = {
  id: 0x0102_0304_0506_0708n,
  name: "Ada Lovelace",
  age: 36,
  active: true,
  score: 99.5,
  favorite: "blue",
  tags: ["math", "engines"],
  data: new Uint8Array([0xde, 0xad, 0xbe, 0xef]),
};

const containerValue: InteropContainer = {
  inner: { value: 7, label: "root" },
  items: [
    { value: 1, label: "one" },
    { value: 2, label: "two" },
  ],
  coords: { x: 400, y: 900 },
};

const listsValue: InteropLists = {
  nums: [1, 2, 65535, 4294967295],
  flags: [true, false, true, true, false],
  names: ["one", "two"],
};

const groupedValue: InteropGrouped = {
  coords: { x: 400, y: 900 },
  label: "grouped",
};

// Hex fixtures below are generated by the Cap'n Proto CLI, for example:
//   printf '(<value>)' | capnp encode tests/fixtures/schemas/interop_matrix.capnp InteropPerson | xxd -p -c 999
const canonicalCases: CanonicalCase<object>[] = [
  {
    name: "InteropPerson",
    codec: InteropPersonCodec,
    value: personValue,
    hex:
      "000000000e0000000000000003000300080706050403020124000000010002000000000000e05840090000006a0000000d000000160000001900000022000000416461204c6f76656c61636500000000050000002a00000005000000420000006d61746800000000656e67696e657300deadbeef00000000",
  },
  {
    name: "InteropPerson.defaults",
    codec: InteropPersonCodec,
    value: {
      id: 0n,
      name: "",
      age: 0,
      active: false,
      score: 0,
      favorite: "red",
      tags: [],
      data: new Uint8Array(0),
    } satisfies InteropPerson,
    hex:
      "00000000070000000000000003000300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    expectEncode: false,
  },
  {
    name: "InteropContainer",
    codec: InteropContainerCodec,
    value: containerValue,
    hex:
      "000000000f00000000000000000003000800000001000100110000002700000028000000010000000700000000000000010000002a000000726f6f7400000000080000000100010001000000000000000900000022000000020000000000000005000000220000006f6e65000000000074776f00000000009001840300000000",
  },
  {
    name: "InteropLists",
    codec: InteropListsCodec,
    value: listsValue,
    hex:
      "000000000b000000000000000000030009000000240000000d000000290000000d000000160000000100000002000000ffff0000ffffffff0d00000000000000050000002200000005000000220000006f6e65000000000074776f0000000000",
  },
  {
    name: "InteropGrouped",
    codec: InteropGroupedCodec,
    value: groupedValue,
    hex:
      "000000000400000000000000010001009001840300000000010000004200000067726f7570656400",
  },
  {
    name: "InteropUnion.text",
    codec: InteropUnionCodec,
    value: {
      which: "text",
      text: "hello",
      number: 99,
      flag: true,
    } satisfies InteropUnion,
    hex:
      "000000000400000000000000010001000000000000000000010000003200000068656c6c6f000000",
  },
  {
    name: "InteropUnion.number",
    codec: InteropUnionCodec,
    value: {
      which: "number",
      number: 4242,
      text: "ignored",
      flag: true,
    } satisfies InteropUnion,
    hex: "0000000003000000000000000100010001000000921000000000000000000000",
  },
  {
    name: "InteropHolder",
    codec: InteropHolderCodec,
    value: {
      cap: { capabilityIndex: 7 },
      dyn: { kind: "interface", capabilityIndex: 9 },
    } satisfies InteropHolder,
    hex: "0000000003000000000000000000020003000000070000000300000009000000",
  },
  {
    name: "PingParams.empty",
    codec: PingParamsCodec,
    value: {} satisfies PingParams,
    hex: "00000000010000000000000000000000",
  },
];

Deno.test("serialization interop snapshots keep canonical fixture bytes stable", () => {
  for (const fixture of canonicalCases) {
    assertStableEncoding(fixture);
  }
});

Deno.test("serialization interop snapshots decode expected generated values", () => {
  const decodedPerson = InteropPersonCodec.decode(
    bytesFromHex(canonicalCases[0].hex),
  );
  assertEquals(decodedPerson.id, personValue.id);
  assertEquals(decodedPerson.name, personValue.name);
  assertEquals(decodedPerson.age, personValue.age);
  assertEquals(decodedPerson.active, true);
  assertEquals(decodedPerson.favorite, "blue");
  assertEquals(decodedPerson.score, 99.5);
  assertBytes(decodedPerson.data, [...personValue.data], "person data");
  assertEquals(decodedPerson.tags.join(","), "math,engines");

  const decodedDefaultPerson = InteropPersonCodec.decode(
    bytesFromHex(canonicalCases[1].hex),
  );
  assertEquals(decodedDefaultPerson.id, 0n);
  assertEquals(decodedDefaultPerson.name, "");
  assertEquals(decodedDefaultPerson.favorite, "red");
  assertEquals(decodedDefaultPerson.tags.length, 0);

  const decodedContainer = InteropContainerCodec.decode(
    bytesFromHex(canonicalCases[2].hex),
  );
  assertEquals(decodedContainer.inner.label, "root");
  assertEquals(decodedContainer.items.length, 2);
  assertEquals(decodedContainer.items[1].label, "two");
  assertEquals(decodedContainer.coords.x, 400);
  assertEquals(decodedContainer.coords.y, 900);

  const decodedLists = InteropListsCodec.decode(
    bytesFromHex(canonicalCases[3].hex),
  );
  assertEquals(decodedLists.nums.join(","), "1,2,65535,4294967295");
  assertEquals(decodedLists.flags.join(","), "true,false,true,true,false");
  assertEquals(decodedLists.names.join(","), "one,two");

  const decodedGrouped = InteropGroupedCodec.decode(
    bytesFromHex(canonicalCases[4].hex),
  );
  assertEquals(decodedGrouped.coords.x, 400);
  assertEquals(decodedGrouped.coords.y, 900);
  assertEquals(decodedGrouped.label, "grouped");

  const decodedTextUnion = InteropUnionCodec.decode(
    bytesFromHex(canonicalCases[5].hex),
  );
  assertEquals(decodedTextUnion.which, "text");
  assertEquals(decodedTextUnion.text, "hello");

  const decodedNumberUnion = InteropUnionCodec.decode(
    bytesFromHex(canonicalCases[6].hex),
  );
  assertEquals(decodedNumberUnion.which, "number");
  assertEquals(decodedNumberUnion.number, 4242);
});

Deno.test("serialization interop snapshots preserve capability pointer indices", () => {
  const decoded = InteropHolderCodec.decode(
    bytesFromHex(canonicalCases[7].hex),
  );
  assert(decoded.cap !== null, "expected interface capability pointer");
  assertEquals(decoded.cap.capabilityIndex, 7);
  assertEquals(decoded.dyn.kind, "interface");
  if (decoded.dyn.kind === "interface") {
    assertEquals(decoded.dyn.capabilityIndex, 9);
  }
});

Deno.test("serialization interop decodes multi-segment far-root fixture", () => {
  const canonical = bytesFromHex(canonicalCases[0].hex);
  const farRoot = toSingleFarRoot(canonical);
  const decoded = InteropPersonCodec.decode(farRoot);
  assertEquals(splitSegments(farRoot).length, 2);
  assertEquals(decoded.id, personValue.id);
  assertEquals(decoded.name, personValue.name);
  assertEquals(decoded.tags.join(","), "math,engines");
});

Deno.test("serialization interop rejects malformed and truncated fixtures", () => {
  const canonical = bytesFromHex(canonicalCases[0].hex);
  assertThrows(
    () =>
      InteropPersonCodec.decode(canonical.subarray(0, canonical.length - 1)),
    /truncated|out of bounds|range/i,
  );
  assertThrows(
    () => InteropPersonCodec.decode(new Uint8Array([0xff, 0x00, 0x00, 0x00])),
    /too short|truncated|out of bounds|range/i,
  );
});
